kaltura/playkit-js

src/engines/html5/media-source/adapters/native-adapter.js
We forgot to actually call load() on the video element.
=> fix(FEC-6971): load video element on native adapter load

src/state/state-manager.js, test/src/state/state-manger.spec.js
Ie11/Edge doesn't trigger playing event after waiting (on seeking), which remains the player on buffering state, so exit from buffering state on seeked event.
=> fix(FEC-7040, FEC-7016, FEC-6946): move from buffering to playing on seeked

src/engines/html5/html5.js
Load the video element itself - used when user gesture is required to start playback.
=> fix(FEC-7108): native load video element for video sibling on mobile 

src/player.js, test/src/player.spec.js
The volume check is not enabling setting 0 or 1
=> fix(FEC-7138): enable setting 0 and 1 values

src/engines/html5/media-source/adapters/native-adapter.js
On bitrate change for progressive download In Android browser (AKA native/stock browser) we have to seek to the current position only after some playback
=> fix(FEC-7089): handle bitrate change in android browser

src/drm/drm-support.js
The current check is validating both OS is Android and Device is mobile, but device in Android land can be the vendor name, e.g. HTC, Sony etc, so need to remove the check.
IMO it's enough to validate that the OS is Android in this case.
=> fix(FEC-7172): fix DRM support test on Android devices

src/player.js
If ads plugin enabled it's his responsibility to preload the content player,
so to avoid loading the player twice which can cause errors on MSEs we are overriding
the configuration and sending preload "none".
=> feat(FEC-7171): handle preload when ads plugin enabled

src/player.js
expose API to get selected engine and stream type.
=> feat(FEC-7101): expose engine and stream type as API

src/player-config.json, src/player.js, test/src/player.spec.js
Align configure api behavior:
**Plugins:**
1. If engine is already created, the existing plugins can update their configuration on the fly. If a new plugin is configured after engine is exists, we will ignore this request.
2. If engine is not yet created, plugins can be either loaded or update their configuration at any time.
**Playback:**
Playback can be configured at any time but this will affect only to until **sources will be configured**.
For example, If sources not yet configured and playback is configured, the playback configuration will take place when sources will received.
If sources already received and playback is configured again, the playback configuration will take place on the next sources configuration.
=> feat: configure refactor

src/player.js, src/plugin/base-plugin.js, test/src/plugin/base-plugin.spec.js
getConfig api should return copy of his config instead of reference.
=> fix(base-plugin): getConfig api should return copy of his config

src/player.js, test/src/player.spec.js
IE11 and some old safari's don't pause on ended. so do it for them.
=> fix(FEC-7071): call pause on ended for browsers which don't do it natively

src/engines/html5/html5.js
`instanceof` check on undefined method caused IE11 and Edge to fail on `oncuechange` event handler, make sure window.VTTCue exist before checking against instance of it.
=> fix(FEC-7238): captions failing on IE11 and Edge

src/player.js, src/track/text-track.js, test/src/track/text-track.spec.js
The comparer func will consider the length of the inputs and return the appropriate comparison accordingly.
=> fix(FEC-7226, FEC-7243): create comparer func to default tracks

flow-typed/interfaces/media-source-adapter.js, src/engines/html5/html5.js, src/engines/html5/media-source/adapters/native-adapter.js, src/engines/html5/media-source/media-source-provider.js, test/src/engines/html5/media-source/adapters/test-adapters/test-adapters.js, test/src/engines/html5/media-source/media-source-provider.spec.js
Change the implementation of preferNative logic for order the MSEs array, instead of return always false in NativeAdapter when preferNative=false.
=> feat: order media source adapters depends on preferNative value

src/player.js, src/track/text-style.js
add default text font-family to text style and expose the TextStyle on the player instance so ENUM is more accessible.
=> feat: add default text font family and expose ENUM

src/engines/html5/html5.js
=> fix(FEC-7317): check if VTTCue and TextTrackCue are not undefined

src/assets/style.css
subtitles are dropping from the top of the player to their correct location in safari 9. it looks like animation.. the correct behaviour would be that the subtitles appears at the bottom of the player.
@OrenMe - seems like there is duplication in the css.. why is there a css file for the subtitles in the playkit-js? isn't all the ui handled in the playkit-ui-js? should i try and remove the whole file?
=> fix(FEC-7242): subtitles transition in safari 9.0

src/player.js, test/src/player.spec.js
on change media we are considering the player config but not to the current state of the following player attributes: 
* muted
* volume
* text language
* audio language
* playback rate
the solution is: 
* saving the state of the attributes above
* considering them (on change media) before player config
=> fix(fec-7334): the player state has not saved on change media

src/engines/html5/media-source/adapters/native-adapter.js
Filter text tracks without language or label.
=> fix: filter empty video element text tracks

src/engines/html5/media-source/adapters/native-adapter.js
This reverts commit 58ada7c707343fb73b9a75cade133988b8ecb8fc.
the filter fix is wrong. 
we have to promote the `index` also for "non valid" track (without language or label) since we consider the `index` in `selectTextTrack`, when we enable the desired track from the video element tracks list which contains the "non valid" track also.
=> revert: "filter empty video element text tracks (#150)"

src/player.js, test/src/player.spec.js
subtitle persist after setting new sources, need to reset the subtitle display state on reset
=> fix(FEC-7335): reset subtitle display on player reset

src/engines/html5/media-source/adapters/native-adapter.js
Sometimes, when playing native hls on Safari, text tracks are not ready on loadeddata event. If this the case, we will wait for canplay event and parse the tracks right after.
=> fix: empty captions menu when playing native hls

src/event/events.js, src/player.js, test/src/event/events.spec.js, test/src/player.spec.js
1. Player should fire enter/exit fullscreen event in case UI app notify him about that.
2. When user use the player API to enter/exit fullscreen, player should requested it from the UI app.
=> feat: handle fullscreen

src/player.js, src/track/track.js, test/src/track/track.spec.js
If the lang comparer receives an empty string as the input lang, it should always returns false (startsWith method will always return true for empty string...)
=> fix(FEC-7380, FEC-7381): there are captions displayed when the captions are supposed to be 'off'

src/engines/html5/media-source/adapters/native-adapter.js
On iOS, when choosing from the native player (AVPlayer) audio track or text track, the player UI wasn't updated. 
This PR bring sync between the player UI and the native UI.
=> feat: handle native selection of tracks

karma.conf.js, src/assets/style.css, src/player.js, src/utils/poster-manager.js
When autoplay is on, the poster might be shown for few miliseconds, which looks buggy.
If autoplay is on & the browser is capable of doing it, I am hiding the poster element .
=> fix(FEC-7355): don't show poster when autoplaying is on

src/engines/html5/html5.js
Sometimes the cuechange event fired before we set the oncuechange handler to the selected text track element.
The solution is first to set the handler and then to change the text track mode.
=> fix(FEC-7504): explicit language is not working on production env 

src/player.js, test/src/player.spec.js
Expose api to get the possible player playback rates
`player.playbackRates; // [0.5, 1, 2, 4]`
Expose api to get the default playback rate
`player.defaultPlaybackRate; // 1`
=> feat: expose playback rates api

src/player.js
`buffered` implementation was empty.
buffered will serve us also in the UI to implement the buffered progress bar (now it's hard coded on 60%).
=> feat: add buffered api

src/player.js
In case the plugins property is undefined (when there are no plugins) the ima check fails, resulting in a load error (which retry resolves! : - ) )
Added protection
=> fix: this._config.plugins.ima check fails if there are no plugins at all

src/engines/html5/html5.js, src/engines/html5/media-source/adapters/native-adapter.js, test/src/engines/html5/media-source/adapters/native-adapter.spec.js
Safari doesn't trigger `durationchange` while live playback. 
we need to trigger it by ourself.
=> fix(FEC-7564): durationchange not triggered while live playback - safari

src/player.js
made the check for ima more accurate. there is nothing wrong with having plugins, it's the just ima plugin we want to avoid
=> fix: canPreload check logic is not accurate

src/engines/html5/html5.js, src/engines/html5/media-source/adapters/native-adapter.js, src/engines/html5/media-source/base-media-source-adapter.js, test/src/engines/html5/media-source/adapters/native-adapter.spec.js
in live when the playback is paused the video element doesn't trigger `timeupdate` event,
this causes the ui (which listens to`timeupdate` to update the `currentTime`) to be out os sync.
=> fix(FEC-7564): trigger timeupdate in case of live when the playback is paused

src/error/code.js, src/error/error.js
* print error for any log level unless off
* change the error message format
=> fix: error printing

src/player.js, test/src/player.spec.js
Raising a flag when the `load` process is starting and blocking another `load` call
=> fix(FEC-7939): 'off' option appears twice after change media

CHANGELOG.md, src/engines/html5/capabilities/html5-autoplay.js, src/player.js
If autoplay capability test fails, try to run muted autoplay and add it to the capability result. 
This will fix also the error message we had in the console if the autoplay failed.
=> fix(FEC-7371): video fails to play on old browsers or browsers with data saver mode on

docs/configuration.md, src/player-config.json, src/player.js
When merging the player config with the media config, in case we didn't received any poster from the user,  we want that the merge result will be the poster from media config.
=> fix: remove default metadata object

flow-typed/interfaces/engine.js, src/engines/html5/html5.js, src/engines/html5/media-source/adapters/native-adapter.js, src/engines/html5/media-source/base-media-source-adapter.js, src/event/event-type.js, src/player.js, test/src/event/event-type.spec.js, test/src/player.spec.js
* Add reset API to player
* Add reset API to engine
* remove src getter of native adapter and use the same implementation in the base adapter.
* Add 4 new events: reset started/ended, destroy started/ended
=> feat(FEC-8079): add reset API to player and use it for change media

src/player.js, src/playkit.js, test/src/player.spec.js
Enable overrding the default player capability results
=> feat(FEC-8083): add setCapability API to allow app to set player capabilities

src/player.js
I emptied the _activeTextCues array when switching to 'off' track, so there won't be any captions to show.
=> fix(FEC-8090): after disabling captions and toggling full screen the last caption frame is displayed

src/player.js
* handle preload in `_handlePreload` method
* check only ima existence in `_canPreload`   
* check auto play capability also for muted as in saver mode is disable 
* when auto play failed check `_canPreload()` before `load`
Depends on https://github.com/kaltura/playkit-js-ui/pull/216
=> fix(FEC-8108): no playback after preroll - android browser

src/player.js, src/track/label-options.js, src/track/label-to-track-map.js, src/track/track.js, src/track/video-track.js, test/src/player.spec.js, test/src/utils/test-utils.js
adding label change callback support
added handling in player.js for customizing the labels.
addded label setter in track.js
updated tests
basic usage would be:
```
config = {
customLabels: {
audio: function(audioTrack) {...},
captions: function(textTrack) {...},
qualities: function(videoTrack) {...}
}
}
```
=> feat(FEC-7330): enable setting custom track labels by app

src/player.js
Reset the sources and metadata objects on player reset.
This enables setting metadata by application between change media.
In general if loadMedia is called player will always prefer the data that comes form the API.
If application wants to supply it's own data it needs to:
```javascript
player.reset();
player.configure({
metadata: {
poster: "MY_POSTER_URL"
}
});
player.loadMedia(...)
```
And in this way player will know that new metadata is required by application and won't prefer data from the API response.
This change also enables calling reset after initial load, that wasn't possible till now, until play was initiated.
=> feat: clear metadata and sources on reset

src/assets/style.css, src/player.js, test/src/player.spec.js
Add black cover div which relays under the poster div and displayed as long as first play didn't happened.
Also, this refactor the way were handled the layers of the playkit container.
The correct layers priority now is (from strongest to weakest):
1. Ads/plugins
2. Poster
3. Black cover
4. Subtitles
5. Video frames
Which gives priority for each layer with no need for use of z-index.
This generated DOM for this order under playkit-container is:
```
<video>
<div class="playkit-subtitles">
<div class="playkit-black-cover">
<div class="playkit-poster">
<div class="playkit-ads-container">
```
=> fix(FEC-7937): video first frame is displayed before pre-roll ad starts

src/player.js, src/plugin/plugin-manager.js, test/src/plugin/plugin-manager.spec.js
Plugin registration fails with error throwing or loading a plugin which was not registered.
This leads to application crash.
Changing this to only alert vie error event and console.info
=> feat(FEC-8244): do not throw plugin load errors on main thread

src/player.js
1. Keep fallback to muted autoplay state.
2. In case user changed the mute value to false we are canceling the fallback to muted state.
3. In case of change media and fallback to mute state is on, fire the fallback to muted event.
4. Handle regular muted autoplay action.
=> fix(FEC-8180): when video starts fallback muted and user select to change media the Unmute icon is not displayed although video still muted

src/state/state-manager.js
Add time update listener to the buffering state
when buffering, if we get a timeupdate event, we need to set the state of the player to playing. (fixes a bug in IE11) the bug is that there is no playing event sent sometimes after it's ended
=> fix(FEC-8272): sometimes when seeking spinner display constantly in IE11

src/engines/html5/media-source/adapters/native-adapter.js
set the current time just after loadeddata event is raised.
=> fix(FEC-8255): video starts from beginning instead 12th sec

src/player.js, test/src/player.spec.js
Do not dispatch text and audio tracks event before start playing.
=> fix(FEC-8319): When starting to play an mp4 video, a TEXT_TRACK_CHANGED event is sent twice

src/player.js, test/src/player.spec.js
Kind of reverts https://github.com/kaltura/playkit-js/commit/c673454e57ec3806e51c170323f4bcfdad7688d7
=> fix(FEC-8354):  When selecting Audio language and refresh the page, the display language returns to default (but actual audio proper)

docs/configuration.md, flow-typed/types/external-caption-object.js, src/track/external-captions-handler.js
checking the 'default' attribute when adding a caption.
updated the docs / type.
=> fix: adding external captions default ability

src/track/external-captions-handler.js
hiding the previous text track, when selecting a new external text track.
=> fix(FEC-8369): toggling between external text tracks does not work

src/engines/html5/media-source/adapters/native-adapter.js
adding config to the constructor of super (BaseMediaSourceAdapter) in nativeadapter.js
=> fix(FEC-8376): when 'Off' should be displayed by default, the external language is displayed

src/plugin/plugin-manager.js, test/src/plugin/plugin-manager.spec.js
Keep the plugin's `disable` value for the next `load` calls
=> fix(FEC-8386): Kava analytics retrieved by default on OTT

src/player.js, test/src/player.spec.js, test/src/track/external-captions-handler.spec.js
instead of calling processCues directly from ` _resetTextCuesAndReposition()`, 
call the `_updateTextDisplay()` because is also checks if we are using native or not.
=> fix(FEC-8419): double captions on ios when toggling fullscreen

src/track/text-track-display.js
Change the font size percent to be closer to the native.
Fixed also by https://github.com/kaltura/playkit-js-ui/pull/257
=> fix: subtitles font size is too small on mobile

src/error/code.js, src/track/external-captions-handler.js
*added a check to see if there is no language, and trigger an error in that case
*refactor `getExternalTracks` function
=> fix(FEC-8411): add protection to validate external text tracks which are added without language

src/engines/html5/capabilities/html5-autoplay.js
Sometimes returning false for autoplay when data saver is on its too strict.
On change media, chrome will allow autoplay even if the data saver is on - on the second media.
=> fix(FEC-8413): on change media with data saver on the player is stuck on the poster

src/engines/html5/media-source/adapters/native-adapter.js
added `_clearHeartbeatTimeout()` to the `abort` event and when destroying the native adapter.
=> fix(FEC-8529): waiting timeout is not cleared on native adapter destroy

src/player.js
always emit the CHANGE_SOURCE_ENDED event so we can have consistent event to get before engine is selected to load a source
relates to FEC-8517
=> feat: emit CHANGE_SOURCE_ENDED on first media load as well

src/player.js
expose error class via player instance to access error enums where playkit-js isn't a dependency.
=> feat(error): expose error class via player instance

src/engines/html5/html5.js, src/engines/html5/media-source/adapters/native-adapter.js
When network disconnects, IE triggers `stall` event, and after the buffer ends it keeps trigger `timeupdate` events (until the network comes back online.. or until forever...) this fix checks if the current time update is greater than the last one - so we know we aren't stuck, and raise an Error.
IE also doesn't change it's state to paused / buffering so we also fire `waiting` event if we are still on playing state but the current time of the player does not change. We trigger `playing` once the player resume playing
=> fix(FEC-7594): native adapter does not raise an error in case network disconnects.

src/player.js, test/src/player.spec.js
Added resize listener to the window, and updated the captions accordingly.
The `_resetTextCuesAndReposition` function acts as a `debounce` function, which will update the captions only after the last resize.
=> fix(FEC-8554): update captions on resize event

docs/configuration.md, flow-typed/types/abr-config.js, src/engines/dropped-frames-watcher.js, src/engines/html5/html5.js, src/player-config.json, test/src/engines/dropped-frames-watcher.spec.js, test/src/engines/html5/html5.spec.js
added the option to disable cap level on fps drop
and added new abr configuration:
```
abr: {
fpsDroppedMonitoringThreshold: number,
fpsDroppedFramesInterval: number,
capLevelOnFPSDrop: boolean
}
```
=> feat(FEC-7808): added the option to disable cap level on fps drop

src/drm/fairplay.js, src/engines/html5/media-source/adapters/fairplay-drm-handler.js, src/engines/html5/media-source/adapters/native-adapter.js, test/src/drm/fairplay.spec.js, test/src/engines/html5/media-source/adapters/fairplay-drm-handler.spec.js
The fairplay hander was managed as a static class and saved the media session on it.
When the player was reset the session wasn't closed and its reference remained on the static class.
=> fix(FEC-8633): HLS fairplay fails with multiple players or consecutive playbacks

src/player.js, test/src/player.spec.js
The event manager is destroyed before the event is dispatched :-)
=> fix(FEC-8621): player destroy event is not dispatched

src/player.js, test/src/player.spec.js
full screen and PIP transitions.
When the player is on PIP and changes to full screen: close the PIP first (otherwise on chrome it will not transition to full screen properly)
When the player is on full screen and changes to PIP: close the full screen first.
=> fix(FEC-8650): the video continues in picture-in-picture window when full screen opened

docs/configuration.md, flow-typed/types/playback-config.js, src/player-config.json, src/player.js
adding the following configuration to disable the picture in picture feature:
```
playback: {
....
pictureInPicutre: false // true by default
}
```
=> feat(FEC-8641): add ability to disable picture in picture

src/track/text-track-display.js
We are using vtt.js parser.
When parsing captions it tries to create an HTMLElement and it also tries to set the localName of it, which is read only, and this causes a crash and captions don't appear.
Docs for HTMLElement.localName:
https://developer.mozilla.org/en-US/docs/Web/API/Element/localName
I don't see any reason to set this anyhow as the creation of an HTMLElement of a certain type also sets its localName by itself.
=> fix(FEC-8668): inline styled vtt parser crash

src/player.js
services that depend on engine must be reset/destroyed before the engine is reset/destroyed as they may depend on reading data from the player before they cleanup.
relates to https://github.com/kaltura/playkit-js-ott-analytics/pull/19
=> fix(FEC-8695): reset/destroy engine only after all services are destroyed

src/player.js
1. creating the player video element before running the capabilities so a click would affect it as well as the video element created in `runCapabilities`
2. set `Player._playerCapabilities = {}` on destroy. Because after a 'click' it is set to `autoplay: true`. After change media - it's not always the case
=> fix(FEC-8714):  change media doesn't work after player.destroy() on iOS

docs/configuration.md, src/track/text-track.js, test/src/engines/html5/media-source/adapters/native-adapter.spec.js
if label does not exist - use the language property.
=> fix(FEC-8715): if label does not exist in manifest use the language property

src/player.js, src/track/external-captions-handler.js
external text track will be active at the beginning in the following scenarios:
1. caption config has 'default: true' and playback.textLanguage is set to auto.
2. caption config has 'default: true' and playback.textLanguage is the same as the caption language.
otherwise, it will be set to false.
=> fix(FEC-8722): more than one caption is checked at the caption menu

src/track/text-track-display.js
instead of relying on the height of the video to determine subtitles size, deciding on the dimention according to the box size. if height > width then using width. else -> using height.
=> fix(FEC-7444): when selecting fullscreen in android captions size is too large

docs/configuration.md, flow-typed/interfaces/engine.js, flow-typed/types/drm-config.js, src/drm/base-drm-protocol.js, src/drm/fairplay.js, src/engines/html5/html5.js, src/engines/html5/media-source/adapters/native-adapter.js, src/engines/html5/media-source/media-source-provider.js, src/player-config.js, src/player.js, test/src/drm/fairplay.spec.js, test/src/engines/html5/media-source/adapters/native-adapter.spec.js, test/src/engines/html5/media-source/adapters/test-adapters/test-adapters.js, test/src/engines/html5/media-source/media-source-provider.spec.js
Add `drm.keySystem` config which specify the drm system to run with. 
This config prior to the [browser-drmSystem map](https://github.com/kaltura/playkit-js/blob/2695cb4a848c259e4b448c09bed68011db18ee2a/src/drm/drm-support.js#L8)
=> feat(FEC-8700): add config option to specify DRM system

src/player.js
Current state: style sheet is selected by id.
change: select it by class, adding playerid for the style sheet class.
=> fix(FEC-8770): iOS -  captions style it applies for both players in the same page

docs/configuration.md
Document the `startTime` affect on ads plugin.
=> docs(FEC-8751): add support for ima playAdsAfterTime setting

docs/configuration.md, src/engines/html5/media-source/adapters/native-adapter.js, src/player-config.js
In some cases (chrome on `preload=auto`, IE after a pause) an additional `timeupdate` is raised by the video element, which initiates the timeout.
1. added protection so it won't start a timeout if the video element is in a paused state.
2. added the ability to configure the timeout by the application
=> fix(FEC-8829, FEC-8807): native adapter throws an error after 30 seconds pause

flow-typed/interfaces/plugin.js, src/player.js, src/plugin/base-plugin.js, src/plugin/plugin-manager.js
plugins life cycle should also have a life cycle method to identify that new media was loaded.
The new life cycle hook will enable returning event listeners or set up internal logic for a new media.
=> fix(FEC-8763): add loadMedia life cycle hook for plugins

src/player.js
fix the selector of the native text cues
=> fix(FEC-8865): the captions style change is not applied on iOS

src/track/external-captions-handler.js
=> fix(FEC-8858): the captions languages in list displayed twice

src/player.js, src/track/text-track-display.js, test/src/player.spec.js
1. Moving base font percentage to 0.58, so the captions will be smaller, like in our previous versions.
2. Adding `resetAllCues` whenever `resetTextCues` is called. (mainly fix seek back captions issues)
=> fix(FEC-8874): captions look and feel issues

src/track/external-captions-handler.js
adding the URL to the HTTP error when fetching a VTT/SRT file
=> fix(FEC-8381): when external caption http request fails, the error message is not clear

src/player.js
Do not handle pre load if any ad plugin exists
=> fix(FEC-8931): when using disableMediaPreload=true, .ts segments are still fired during bumper

src/utils/resize-watcher.js
The issue was because the new iFrame was on top of the ads container and blocked it.
Initializing the resizeObserver only once, no need to initialize it on every reset (as long it's the same video element).
=> fix(FEC-8957): cannot pause/resume the ad after change media on iOS

src/fullscreen/fullscreen-controller.js, src/player.js, test/src/player.spec.js
Change html element to id and add check for ios fullscreen (#353)
=> fix(FEC-8826): pass html element from api and there isn't check for ios in isfullscreen method

src/fullscreen/fullscreen-controller.js
Add playsinline config for making inBrowserFullscreen to be relevant only when playsinline true otherwise it will play native, as expected
=> fix(FEC-9021): [iOS] - different behaviour after closing fullscreen and enter fullscreen again

src/fullscreen/fullscreen-controller.js
shaka creates a new fullscreen event and dispatch it, add fullscreen flag to avoid from player to dispatch twice
=> fix(FEC-9037): When entering/exiting fullscreen, the events are sent twice

src/player.js
When we get in the configuration that mediatype is vod and the asset is live we return that the player is in live state - the actual result here should be that the player will load in VOD mode and not in Live mode (UI)
The change was to add a check that isLive in the player will return false if explicitly set as type VOD
=> FEC-9012 - We dont read mediaType VOD configuration

src/fullscreen/fullscreen-controller.js
[Deprecation] 'HTMLVideoElement.webkitDisplayingFullscreen' is deprecated. relevant only for ios devices
=> fix(FEC-9041): 'HTMLVideoElement.webkitDisplayingFullscreen' deprecation warning

src/utils/env.js
Use UAParser enum for device type and add check for webos smart tv as extend of this lib.
=> fix(FEC-9177): Smart TV showed as mobile device

src/engines/html5/media-source/adapters/native-adapter.js
LG have static duration and they are jumping back when in safari they are changing the duration.
LG jumping 15 sec back on the first 15 available and 10 sec after so this._lastTimeUpdate will never be lower than this._videoElement.currentTime after first time.
whenever they are equal only we would like to fire waiting event because we are actually weren't moved.
=> fix(FEC-9187): LG TV different  behavior for LIVE

flow-typed/interfaces/ads-plugin-controller.js, src/ads/ads-controller.js
`IAdsPluginController` exposes `name` to filter bumper controller
(`controller.constructor.name` doesn't work in transpiled files)
=> fix(FEC-9192): post bumper doesn't play

src/player.js
add check for non linear ads for attachMediaSource/detachMediaSource, shouldn't use attachMediaSource/detachMediaSource with non-linear ads
=> fix(FEC-9261): playback doesn't play with non-linear ads

src/track/text-track-display.js, src/track/vtt-cue.js
cue attribute changed from `middle` to `center`.
=> fix(FEC-9243): external subtitles fail on safari due to invalid cue attribute

flow-typed/interfaces/engine-decorator.js, flow-typed/interfaces/engine.js, flow-typed/interfaces/media-source-adapter.js, src/engines/html5/html5.js, src/engines/html5/media-source/base-media-source-adapter.js, src/player.js
Add support for replay after ads finish to return to beginning. 
fix bug engine.ended on `attachMediaSource` will not give always true on the end of the media as expected, instead on `detachMediaSource` which will return true when ad playing and decorator is active or when decorator is not active engine will return true from video element.
keeps the value form `detachMediaSource` to know in `attachMediaSource` if media ended.
=> fix(FEC-9262): playback doesn't return to start after playback with ads in LG TV

src/track/text-track-display.js
Add support for older browsers for cue.align = middle
=> fix(FEC-9274): older browser doesn't support cue.align=center

src/fullscreen/fullscreen-controller.js, test/src/fullscreen/fullscreen-controller.spec.js
**Problem**: config doesn't changed yet on controller.
**Solution**: remove config from controller state to keep the configuration up to date from player.
`exitFullscreen` will check the state of non native fullscreen mode instead checking the config, `enterFullscreen` will check the config for fullscreen mode
=> fix(FEC-9277): inBrowserFullscreen doesn't work on ios

src/assets/style.css
When a user resize browser / element a resize event is used to relayout everything. As this is a bug in the player, the mentioned functionality and any other that rely on resize will not work.
=> fix(FEC-9283): trigger RESIZE events in Firefox

src/player.js
add check for engine existence
This may happen when trying to load a media for first time where player doesn’t have an engine for it.
We init the reset flag and then when another loadMedia is called or just calling rest method the reset flag is set and we will go into reset calling the engine reset method although engine is not set.
We already have this protection in destroy for calling engine so this was required in reset as well.
=> fix(FEC-9291): player without engine get error after reset

src/utils/env.js
fix fake safari for Samsung TV browser detection.
=> fix: browser detection for samsung

src/error/code.js, src/player.js, src/plugin/plugin-manager.js
**Issues:**
1. An unhandled exception from plugin not handled
2. The plugin manager throws loading error instead of dispatching error event 
**Solution:**
dispatching an error event from the player for both unhandled exception and loading error
=> fix: plugin exception handling

flow-typed/interfaces/engine-capabilty.js, src/engines/html5/capabilities/html5-autoplay.js, src/engines/html5/html5.js, src/player.js
`playsinline` false on IOS can't play automatically medias and audio instead fix the weird behaviour.
ACT:IOS try to start playing instead return false from capability check
EXP: won't try to start playing when it's not possible.
SOL: add `playsinline` config to autoplay capability check instead set false.
=> fix(FEC-9313): weird behaviour IOS when configuration autoplay native 

src/ads/ads-controller.js
* pass the `ads` array by value (by `slice()`) to avoid change the original config
* call to `_addBindings()` on reset
=> fix(FEC-9385): new ad layout, in playlist the ads playing for one entry only

src/player.js, src/state/state-manager.js
* move to `idle` when the postroll (dai) is done
* make sure the engine events fired by the engine itself not by the proxy
=> fix(FEC-9333): when playing a playlist and closing the countdown window, the next entry starts automatically

src/ads/ads-controller.js, src/player.js
**Issue:** Comes from https://github.com/kaltura/playkit-js/pull/324/files#diff-29cfd888e32c875acb1a2dd113e516dbR1628
**Solution:** Hide the poster only on `AD_STARTED`
Solves [FEC-9434](https://kaltura.atlassian.net/browse/FEC-9434)
=> fix(FEC-9434): the first frame of content flashes for a second before the ad playback.

src/engines/html5/html5.js
Due to a bug in shaka pip_webkit which sets pictureInPictureEnabled to true in unsupported devices like iphones we will first rely on the response of webkitSupportsPresentationMode (if exists) and only if not on the pictureInPictureEnabled property
The fix has been tested on Android Chrome, Mac Chrome and Safari, XCode iphone and ipad simulator
=> fix(FEC-9420): PIP button is showed but not working

flow-typed/interfaces/engine.js, src/player.js
pass the player id to the engine creation to use the already prepared one (was missing in mistake)
=> fix(FEC-9510): auto play failed in ios

src/ads/ads-controller.js
Do not run the ended flow while ad is loading
(This is for the new ad layout. The same issue with ima vmap fixed by https://github.com/kaltura/playkit-js-ui/pull/454)
Solves [FEC-9493](https://kaltura.atlassian.net/browse/FEC-9493)
=> fix(FEC-9493): new ad layout - dragging to the end causes the midroll to play with replay button

src/player.js, test/src/player.spec.js
Show the poster once `AUTOPLAY_FAILED`
Solves [FEC-9527](https://kaltura.atlassian.net/browse/FEC-9527)
=> fix(FEC-9527): The poster is hidden when auto play is failed

flow-typed/interfaces/engine.js, src/ads/ad-event-type.js, src/engines/html5/html5.js, src/player.js, test/src/player.spec.js
* New `AD_AUTOPLAY_FAILED` event
* Fire `AUTOPLAY_FAILED` once get `AD_AUTOPLAY_FAILED `
* Html5 returns the play promise (required when a plugin plays an ad using the engine)
Solves [FEC-9513](https://kaltura.atlassian.net/browse/FEC-9513)
=> fix(FEC-9513): bumper - endless spinner when auto play is failed

src/engines/html5/media-source/adapters/native-adapter.js
Issue: promise resolve on the next tick so video load and then we are setting the src, no src on loading.
Solution: handle the load when promise resolve
Solve: FEC-9583.
=> fix(FEC-9583): race condition on load ios playback

src/player.js, test/src/middleware/playback-middleware.spec.js
The issue is when only `load` middleware implemented.
**Issue**: 
`play` calls to `_play` immediately (as no `play` middleware provided). Then `_play` calls to `_load` and actually bypasses the `load` middleware mechanism.
**Solution**: 
`_play` doesn't call to `_load`. only `play` calls to `load`
Solves FEC-9459
=> fix(FEC-9459): load implementation in middleware is not working as expected

src/player.js
**Issue**: 
The first click loads the ad and the bumper but not the playback source. then the playback play failed as 'no-user-gesture'
**Solution**: 
Prepare the playback video element once click
Solves FEC-9585
=> fix(FEC-9585): when pre-roll+bumper exist need re-click to play the content - iOS

src/ads/ads-controller.js, test/src/ads/ads-controller.spec.js
mark all ads as `played` when playing the post-roll
Solves FEC-9600
=> fix(FEC-9600): new ad layout - pre-mid-post rolls - no replay button appears after post-roll ad finished

src/engines/html5/html5.js, src/player.js, test/src/player.spec.js
Issue: load doesn't call on play after attach detach.
Solution: add load to attachMedia.
pause and hideTextTracks added to avoid textTracks and update state of player after detach.
Solve FEC-9603.
=> fix(FEC-9603): load doesn't call on play after attach detach

src/track/text-track-display.js
Added an the window declaration to the `moveBoxToLinePosition` function and call.
=> fix(FEC-9614): Player is stuck when having empty lines on VTT on E11

flow-typed/interfaces/engine-capabilty.js, flow-typed/interfaces/engine.js, src/engines/html5/capabilities/html5-autoplay.js, src/engines/html5/html5.js, src/player.js, src/utils/env.js, test/src/player.spec.js
**Issue**: Hisense can't contain base64 as source.
**Solution**: add the set capability to engines and then handle it inside the engines, add partial possibility assignment the rest capability will be checked as well, if not needed it won't check.
add regex to detect correctly hisense TV and add smart tv detection fallback for tv which doesn't support yet.
Depends on https://github.com/kaltura/kaltura-player-js/pull/298
Solves FEC-9577
=> fix(FEC-9577): Hisense playback doesn't work

src/player.js, src/state/state-manager.js
to fix bug in hls that seek event is fired when changing qualities - if state was idle (i.e end of playback) and seeked event fired don't change state to paused if current time is at the end of the playback
solves FEC-9534
=> fix(FEC-9534): changing the bitrate post completion of any content changes replay to play icon

flow-typed/interfaces/engine-capabilty.js, src/engines/html5/capabilities/html5-autoplay.js, src/engines/html5/html5.js, src/player.js
This reverts commit 1b4a3ca as is unneeded any more due to https://github.com/kaltura/kaltura-player-js/pull/302
Solves FEC-9629
=> fix(FEC-9629): Player is not inline when rendered after the DOM loads

src/track/text-track-display.js
changed fallback to lineHeight so it cannot be 0 not only for ie8 (otherwise it gets into an infinite while loop)
solves FEC-9614
=> fix(FEC-9614): players get stuck when there are empty captions in ie11

src/track/text-track-display.js
Added brackets so lineHeight can never be 0
Solves FEC-9614
=> fix(FEC-9614): players get stuck when there are empty captions in ie11 - additional fix

src/engines/html5/html5.js, src/engines/html5/media-source/adapters/fairplay-drm-handler.js, src/engines/html5/media-source/adapters/native-adapter.js, src/event/event-type.js, src/player.js
Created new CustomEventType DRM_LICENSE_RESPONSE which bubble till the player and added code to FairplayDrmHandler to calc the license time from request to response
Solves FEC-9109
=> feat(FEC-9109): add DRM Load time metric

src/player.js, test/src/player.spec.js
don't call `load` if `src` already exists
Sloves FEC-9605
=> fix(FEC-9605): load middleware called twice when preload is 'auto'

docs/configuration.md, flow-typed/types/response.js, src/engines/html5/media-source/adapters/fairplay-drm-handler.js, src/utils/util.js, test/src/engines/html5/media-source/adapters/fairplay-drm-handler.spec.js, test/src/engines/html5/media-source/adapters/native-adapter.spec.js, test/src/utils/util.spec.js
* add `url, originalUrl, header` to the `responseFilter` handler
* add `PKResponseObject` type with `url, originalUrl, data, headers`
* add new util `Http. convertHeadersToDictionary`
=> feat: enrich the response filter params

src/player.js
if the current time is negative then it means that the player is out of the DVR window.
DVR out of the window should seek to live edge.
Solve FEC-9997.
=> fix(FEC-9997): out of DVR window will lead to live edge

src/engines/html5/media-source/adapters/native-adapter.js
The player is broken when switching between tabs or just minimising Safari.
The original issue has occurred here FEC-8873  however was resolved only for ad use case.
In addition, the main issue is still occuring and the bug is still open with apple: https://bugs.webkit.org/show_bug.cgi?id=195452
As a current solutions I have implemented a nudge to the seek in order to bypass the issue when returning from "Idle" mode.
=> fix(FEC-10014): Content playback fails when user minimise the browser on IOS

src/engines/html5/html5.js, src/engines/html5/media-source/adapters/native-adapter.js, test/src/engines/html5/html5.spec.js, test/src/engines/html5/media-source/adapters/native-adapter.spec.js
destroy dropped frames watcher on reset to avoid a memory leak.
clear the DRM selection for the use case of loading another media without DRM keeps selection.
=> fix(FEC-10122): clear drop frame watcher and DRM selection

src/player.js
IMA probably changed their adloaded timing which causes issues on our logic of playing ads with MSE.
issue: video detached 6-8 sec before midroll supposes to show up which causes an empty video tag.
Solution: detach the media when the ad break starts.
Solve FEC-10335.
=> fix(FEC-10335): ad doesn't play correctly on same video tag with MSE

src/engines/html5/html5.js
issue: iPhone 7 ios 13.5.1, iPhone 7 change metadata track to disable after our timeout for that issue called.
solution: change the timeout to listener to change event to avoid this scenario of incorrect timing.
Solve: FEC-10266.
=> fix(FEC-10266): Ima dai doesn't show ad preset

src/player.js, test/src/player.spec.js
Move `PLAYBACK_START` back to playkit for autoplay flow
(The only reason we moved it to kaltura player is to be aligned with PLAYBACK_ENDED)
Revert part of commit 9b5ed58
Solves FEC-10468
=> fix(FEC-10468): PLAYBACK_START not fired on autoplay

docs/configuration.md, src/fullscreen/fullscreen-controller.js
Start the document listener only on fullscreen request.
In this way, only the specific player will listen to those events.
=> fix(FEC-10485): When multi players on page, 'enterfullscreen' event triggers by all players

.babelrc, src/engines/html5/html5.js
issue: HTML5 event handler is too complex and took too long and the babel config causes memory issue on a smart TV.
Solution: simplify the handler and fix the babel plugin config which causes the memory issue.
=> fix(FEC-10512): handle memory leaks in smart TV

src/fullscreen/fullscreen-controller.js
Add flag to overcome browsers which supports more than one fullscreenchange event.
=> fix(FEC-10516): Fullscreen event dispatched twice from the player

src/track/text-track-display.js
* Handle the VTT property `align: left/right` (like `positionAlign: start/end`)
* Protect the cue width and height to not exceed the caption area
Solves FEC-10451
=> fix(FEC-10451): captions misaligned in V7 VTT

src/engines/html5/html5.js, src/player.js
* Don't use `exitPictureInPicture` when it's native PiP but use `webkitSetPresentationMode('inline')`
* Remove the redundant `LEAVE_PICTURE_IN_PICTURE` firing. it's already fired natively. 
Solves FEC-10510
=> fix(FEC-10510): iOS14 -  cannot exit from native PiP by the player's PiP button

src/fullscreen/fullscreen-controller.js
* Fix `isFullscreen` - was return `true` on PiP
* exit from PiP before applying full screen
Solves FEC-10513
=> fix(FEC-10513): iOS14 -  cannot enter to full screen from PiP

src/player.js
Don't pause once ready. 
This was right before the load was middleware. 
Also, it's redundant because the player it's already paused and moved to the `PAUSED` state by `METADATA_LOADED` 
Solves FEC-10681
=> fix(FEC-10681): pre roll stuck half way or doesn't allow the content to start playing on iphone and chrome

src/engines/html5/html5.js
Issue: source has been removed from video tag before destroy has been finished.
Solution: wait for mediaSource destroy before removing the src from video tag.
=> fix(FEC-10662): source removed before destroy process finish

src/player.js
Issue: seek on low-level device could take a few seconds, remove it when it's not needed.
Solution: on the first play we're already on edge so it's redundant.
Solves FEC-10643
=> fix(FEC-10643): seek to live edge on first play redundant

docs/configuration.md, flow-typed/types/playback-config.js, flow-typed/types/screen-orientation-type.js, src/fullscreen/fullscreen-controller.js, src/player-config.js, src/player.js, src/playkit.js, src/screen-orientation-type.js
add screenLockOrientionMode config to be able to lock the screen mode in fullscreen.
new enum with possible values for this config:
`"none"
"any"
"natural"
"landscape"
"portrait"
"portrait-primary"
"portrait-secondary"
"landscape-primary"
"landscape-secondary"`
Solves FEC-10486
=> feat(FEC-10486): Lock orientation according to screenLockOrientionMode config when switching to full screen

src/state/state-manager.js, src/state/state-type.js
Issue: seek and the buffer was signaled as the same state in the player - couldn't be able to find the difference between the real buffer and seeking.
Solution: add a new state for seeking to make sure it won't signal as a buffer.
=> feat(FEC-10682): signal seek in different way from buffering.

src/engines/html5/media-source/adapters/native-adapter.js, src/player.js, src/track/external-captions-handler.js, test/src/configs/external-captions.json, test/src/player.spec.js
Issue: external tracks on native still exist on player tracks API and for next media.
Solution: add a track called playkit-external-track for external tracks and don't expose it on API.
=> fix(FEC-10679): external native text track still existing on API for next media

src/state/state-manager.js, test/src/configs/external-captions.json
When buffering on live content, the order of events that triggered from the video element is: 
1. `playing`
2. `waiting`
3. `timeupdate`
(this is true for all browsers except IE)
Because we're triggering `playing` on `timeupdate` event we're causing Youbora to report end of buffer when the player is actually still buffering.
The solution is to exclude this logic only to IE.
=> fix(FEC-10760): Youbora - bufferUnderrun event fired when buffering started and no bufferDuration in Ping events

src/engines/html5/html5.js, src/event/event-type.js, src/player.js
Issue: addTrack on safari add the track to the first position on TextTrackList.
Solution: register after native tracks loaded to addtexttrack to make sure if new tracks adding on index 0 it'll change the indexes for all tracks otherwise it won't change it.
=> fix: CEA708 subtitle doesn't get correct index on native 

src/player.js
Issue: audio stream has a black screen when it plays.
Solution: check if it's audio by sources.type and keep the poster.
=> fix(FEC-10564): keep the poster for display for an audio-only entry

docs/configuration.md, flow-typed/types/playback-config.js, flow-typed/types/text-config.js, flow-typed/types/text-style.js, src/engines/html5/media-source/adapters/native-adapter.js, src/player-config.js, src/player.js, src/track/external-captions-handler.js, src/track/text-style.js, test/src/engines/html5/media-source/adapters/native-adapter.spec.js, test/src/player.spec.js, test/src/state/state-manger.spec.js, test/src/utils/test-utils.js
Issue: text track doesn't have a config for styling, there is only an API for styling.
Solution: create a text container for the text track and add the options for styling the text track.
Add an option to disable external setting by set attribute explicit as null or ''.
fix test: should dispatch new state event - updateState dispatch the event so two events dispatched cause FEC-10760
=> feat(FEC-10766): create text config section and option for styling

src/track/text-style.js, test/src/player.spec.js
Issue: the condition of || doesn't work properly with 0 as the current value and always takes the default option.
Solution: create the default values as a static getter to be able to use it on static methods and on the first initialize of the properties.
merge the setting and default value to make sure all set correctly.
add relevant tests.
=> fix(FEC-10844): advanced caption settings custom caption is always marked even when choose sample

src/player.js
Issue: config used previous config
Solution: change the config to new config
=> fix(FEC-10878): order of text captions are broken on Safari browser

src/engines/html5/media-source/adapters/native-adapter.js, src/player.js
Issue: for the first selection safari doesn't fire the addTrack event yet to handle the change in the indexes(timing issue).
Solution: add native container to handle the text track by index decided once it parsed. (same as we did on hls adapter)
=> fix(FEC-10879): Safari ignores explicit text track

src/assets/style.css, src/player.js
Issue: subtitles container append before poster and located under it on the DOM tree.
Solution: poster, captions, and black screen container blocking user action from UI add pointer-events: none to avoid it.
append captions container after playkit containers.
=> fix(FEC-10890): the captions aren't displayed for audio entry and UI doesn't clickable.

docs/configuration.md, flow-typed/types/network-config.js, src/error/code.js, src/player-config.js
* Add default configuration for `maxStaleLevelReloads`.
* Update docs.
=> feat(FEC-10657): add max stale level reloads config

src/player.js
We used to rely on fullscreen event to change captions size and position. this event used to fire before screen dimensions were settled.
We now use a more precise resize observer manager and can remove the delay that causes a blinking effect.
=> feat(FEC-10925): remove captions update delay

flow-typed/types/ad-options.js, src/engines/engine-decorator.js
Issue: IMA and DAI don't work in parallel.
decorator selection could take one value from one decorator and another one from the second if it's not implemented on the first one.
Solution: add inStream to avoid attach detach for DAI.
check if the decorator doesn't have the prop after we get the active and make sure we're using always the first one if two decorators are active.
=> fix(FEC-10041): Allow IMA and IMA DAI to be used in parallel

docs/configuration.md, src/player-config.js
remove `defaultBandwidthEstimate` from `player-config.js`
=> feat(FEC-10915): let shaka and hls.js use their own default bandwidth estimators

src/player.js
Issue: black screen when play request and playing delayed.
Solution: keep the poster as far as possible.
FEC-10823.
=> fix(FEC-10823): change initial poster hiding to first playing or ad playing

src/player.js
When vtt file is sliced it sometimes may contain same caption line in both slices of the vtt file as the time range of it is crossing the slicing border.
If the line has a trailing whitespace it will be treated differently if it is in the end of the vtt slice or at the start(or middle) as we trim the entire vtt fragment we get but not the individual time blocks.
Example:
```
Frag1.vtt
WEB VTT
1
00:00:00.360 --&gt; 00:00:01.520 
first line
2
00:00:01.600 --&gt; 00:00:02.680 
second line ending with trailing whitespace
```
```
Frag2.vtt
WEB VTT
3
00:00:01.600 --&gt; 00:00:02.680 
second line ending with trailing whitespace 
4
00:00:03.400 --&gt; 00:00:04.000
third line
```
In the first fragment we will clip the trailing whitespace cause we do it in webvtt-parser for the entire frag before …
=> fix(FEC-10963): filter duplicate captions

src/engines/engine-decorator.js, src/engines/html5/html5.js, src/engines/html5/media-source/adapters/native-adapter.js, src/player.js
Issue: engine doesn't expose an error for playback error, it dispatched from the player instead - the engine decorator can't ignore the playback error.
Solution: change the dispatch from the player to the engine to make sure the playback error could reject on the engine decorator.
tests failed for scenario _nativeTextTracksMap has index 0 and 2(metadata between) so for raise an error when it gets to i = 1 that doesn't exist.
=> fix(FEC-11035): playback error dispatch from player instead of from engine

flow-typed/interfaces/engine.js, flow-typed/interfaces/media-source-adapter.js, src/engines/html5/html5.js, src/player.js
Add `selectImageTrack` implementation.
=> feat(FEC-10941): Use In-Stream DASH thumbnails on the timeline

src/player.js
Issue: shaka stall detector calling pause and play before first play promise resolved, it cause DOM exception and playback stop after this pause. flow is playback play() -> stall detector pause() play() -> play failed handler pause().
Solution: remove the pause from play failed handler since after play is failed browser handle it.
=> fix(FEC-11082): DOM play error on SmartTV on when stall happen on the beginning

src/engines/html5/html5.js
**Issues**: 
>   1. catch once resolve the promise chain for next.
>   2. Multiple load promises created by multiple load calls.
**Solution**: 
> 1. return promise reject to reject the chain 
> 2. create the loadPromise once until we'll get a reset or destroy.
=> fix(FEC-11035): catch resolve the promise chain and load create promise for each call.

src/engines/html5/media-source/adapters/native-adapter.js
When the browser is triggering a waiting event, the browser should also trigger a playing event afterwards, but doesn't do so.
solution - Add listeners to waiting and playing events in native adapter, that update waiting event flag accordingly.
Solves [FEC-11108](https://kaltura.atlassian.net/browse/FEC-11108)
=> fix(FEC-11108): loading spinner after unmuting on Safari

src/engines/engine-decorator.js
fix null pointer in the engine decorator (when `target[prop]` is `null`)
=> fix(FEC-11119): VR (360) media doesn't work on safari browser - no video displayed

src/track/external-captions-handler.js
`textTracks` not always appears on the video element object since different engines return different object types.
Solves FEC-11118
=> fix(FEC-11118): video doesn't play, player crushes the application

src/engines/html5/media-source/adapters/native-adapter.js
issue:
in safari spinner is displayed while changing the focus.
solution:
limit event listener "focus" only to IOS.
Solves FEC-11145
=> fix(FEC-11145): spinner is displayed while changing the focus

src/player.js
reset the both internal and external captions on resize and full screen change
Solves FEC-11054
=> fix(FEC-11054): subtitle container width is not getting reset when user exits full screen mode

src/player.js
issue: calling getThumbnail on undefined engine.
solution: checking if engine is defined before calling engine.getThumbnail().
Solves FEC-11188 / [SUP-27405](https://kaltura.atlassian.net/browse/SUP-27405)
=> fix(FEC-11188): getThumbnail is failing when engine is undefined

src/fullscreen/fullscreen-controller.js
Issue: Captions on the native player are cut and misplaced in the first few seconds.
`IsFullscreen` returns an incorrect response in IOS.
Solution: add the custom flag for ios fullscreen request.
Fix the caption issue as well.
The flag indicates that a specific player is in fullscreen.
=> fix(FEC-11277): native IOS isFullscreen doesn't response correct answer

src/fullscreen/fullscreen-controller.js, test/src/fullscreen/fullscreen-controller.spec.js
issue: Captions on the native player are cut and misplaced in the first few seconds.
playsinline=false starts in fullscreen without any indication.
Solution: split the check for IOS since it is relevant for specific player fullscreen status.
Solves FEC-11280
=> fix(FEC-11280): IOS playsinline=false doesn't response correctly for isFullScreen

src/fullscreen/fullscreen-controller.js
Issue: in iOS14 `webkitDisplayingFullscreen` is not reliable for fullscreen active- it changed to `true` a bit after `webkitbeginfullscreen` triggered
Solutions: use `webkitPresentationMode === 'fullscreen'` for fullscreen active where applicable
=> fix(FEC-11277): iOS14 - captions on native player are cut and misplaced in the first few seconds

src/utils/util.js
the issue:
when in KMC TV Platform Studio -> trying to preview a playlist, sometimes the page keeps loading non-stop because an element is undefined.
the solution:
checking if the element is defined before using it.
=> fix(FEC-11311): TV Platform Studio unable to preview playlist

src/track/external-captions-handler.js
Internet Explorer 11 does not support VTTCue api and therefore throws an invalid argument error when trying to call addCue(cue) on native track with cue which is instance of VTTCue instead of TextTrackCue
=> fix(FEC-11414):  Externals text tracks with native subtitles not supported on IE 11

src/player.js, src/track/track.js, test/src/track/track.spec.js
**issue:**
when playing a playlist which its entries have at least 2 matching prefix of key languages (i.e. "zh" and "zh_tw"), and switching from one entry to another, the caption selection in player changes.
**solution:**
adding equality check in langComparer().
first seeking for an identical caption language, then for prefix.
Solves [FEC-11467](https://kaltura.atlassian.net/browse/FEC-11467)
=> fix(FEC-11467): caption selection changes across entries in playlists

src/player.js
checking if player should seek to live edge after playing pre-roll ads, when streaming live.
Solves FEC-11435
=> fix(FEC-11435): player not seeking to live edge after preroll ads

package.json, src/track/external-captions-handler.js, test/src/track/external-captions-handler.spec.js
**Captions on Safari - Captions icon missing on specific entry on V7 player 1.11.1 (regression)**
When running on Safari (seen both on Mac or iPad)
Captions icon missing on specific entry on V7 player 1.11.1 (regression)
**bug :** the ExternalCaptionHandler prevents duplicate tracks from being added to the list of tracks by comparing the external track to the existing tracks.
**fix:** that the comparison will be made only in relation to the availability tracks
solves: (FEC-11484)
=> fix: (FEC-11484): safari - captions icon missing on specific entry (regression)

docs/api.md, flow-typed/types/text-style.js, src/track/text-style.js, src/track/text-track-display.js, test/src/player.spec.js
Modify default font size to 100%.
Remove uses of fontScale and expose fontSize in API.
Fixes FEC-11510.
Related PRs: 
https://github.com/kaltura/playkit-js-ui/pull/639.
https://github.com/kaltura/kaltura-player-js/pull/491
=> fix(FEC-11510): No default font size selected in cvaa

docs/api.md, flow-typed/types/text-style.js, src/track/text-style.js, test/src/player.spec.js
Re-add fontScale to textStyle for backward compatibility.
Fixes FEC-11537.
=> fix(FEC-11537): Need to re-add fontScale to textStyle config for backward compatability

flow-typed/types/exteranl-thumbnails-object.js, src/thumbnail/external-thumbnails-handler.js, test/src/assets/thumbnails1.vtt, test/src/assets/thumbnails2.vtt, test/src/assets/thumbnails3.vtt, test/src/thumbnail/external-thumbnails-handler.spec.js
Currently the thumbnalils images URL is relative to the application domain by default, Although the convention is that they should be relative to the vtt file adress
solves: FEC-11547
related pr: https://github.com/kaltura/kaltura-player-js/pull/494
=> fix(FEC-11547): The thumbnalils images should be relative to the VTT file adress by default

src/engines/html5/html5.js
TIMED_METADATA event payload contains label to define which TextTrack dispatched event
=> fix(FEC-11606): Add TextTrack label to TIMED_METADATA event payload

src/engines/html5/media-source/adapters/native-adapter.js
***issue:***  look at _getParsedTextTracks() on https://github.com/kaltura/playkit-js/blob/master/src/engines/html5/media-source/adapters/native-adapter.js#L696
when this method called at the second time (like after calling changeMedie() in this case) the textTracks including the external text trcak.
and the first condition evaluates to false and therefore the indexes start from 1 instead of 0 which leads to an incorrect index value (that is - same index for two different tracks) on the getExternalTracks() method in (https://github.com/kaltura/playkit-js/blob/master/src/track/external-captions-handler.js#L118) since  it is relying on the textTracks.langth.
and that bring the method the _markActiveTrack(track: Track) method on https://github.com/kaltura/playkit-js/blob/master/src/player.js# …
=> fix(FEC-11655): System highlights 2 options (captions) after clicking the "Change media" button on Safari

src/engines/html5/html5.js
dont turn off the metadata track listener when selecting a text track
=> fix(FEC-11645): id3 metadata doesn't fired when streaming with captions

flow-typed/types/metadata-config.js, src/player.js
add setSourcesMetadata api (to enable dynamically cofigure the epgId (programId) in the sources.metadata)
related pr:
https://github.com/kaltura/playkit-js-providers/pull/155
https://github.com/kaltura/playkit-js-ott-analytics/pull/64
https://github.com/kaltura/kaltura-player-js/pull/504
https://github.com/kaltura/kaltura-player-js/pull/503
=> fix(FEC-11611): Pass the program ID when sending a bookmark

flow-typed/interfaces/engine.js, flow-typed/types/text-track-cue.js, src/engines/html5/html5.js, src/player.js, src/playkit.js, src/track/cue-point.js, src/track/external-captions-handler.js
add a new api `getTextTracks` to get the native video text tracks
add a new type `TextTrackCue`
add a new class `CuePoint`  
and `CuePoint.TYPE` - `EMSG` for emsg and `CUSTOM` for custom cue points
add a new function `createTextTrackCue` to create `TextTrackCue` for a `CuePoint` 
Related to https://github.com/kaltura/kaltura-player-js/pull/509, https://github.com/kaltura/playkit-js-dash/pull/172
Solves FEC-11632
=> feat(FEC-11632): expose stream timed metadata

src/engines/html5/media-source/adapters/native-adapter.js
***issue:*** the native-adapter failed to set the duration on onlodedeData event properly since it is too early
***fix:*** move the duration setting to the play event (on live)
solves: FEC-11744
=> (FEC-11744): Player_Web_Mac_Safari - Start Over button moves program to live position (when you click on it for 2nd time and more)

flow-typed/interfaces/media-source-adapter.js, src/engines/html5/html5.js, src/engines/html5/media-source/adapters/native-adapter.js, src/engines/html5/media-source/base-media-source-adapter.js
**issue:** in live stream played on safari when you seek back to - 0 (start over), the currentTime jump to live edge (and equal to duration) for a few ms before resets back to 0, making the isOnLiveEdge() logic on the engine to evalute to false
**fix:** move the isOnLiveEdge() api defenition to the adapters level and let the native adapter to overide the logic and return false by default as long as currentTime resetting was not completed
solves: FEC-11745
=> fix(FEC-11745): Player_Web_Mac_Safari - Flash of live stream after Start Over

src/engines/html5/html5.js, src/event/event-type.js, src/player.js, src/playkit.js, src/track/cue-point.js, src/track/text-track.js, src/track/timed-metadata.js, src/utils/binary-search.js, src/utils/index.js, test/src/player.spec.js, test/src/utils/binary-search.spec.js
* new type `TimedMetadata` instead of `CuePoint`
* new `TIMED_METADATA_CHANGE` event which triggered when with `TIMED_METADATA` but with payload of `TimedMetadata` array instead of `VttCue` array
* remove `track.label` and merge all metadata tracks cues instead (reverts https://github.com/kaltura/playkit-js/pull/609, closes https://github.com/kaltura/playkit-js/pull/610)
* new function `createTimedMetadata` to create a `TimedMetadata` based on `VttCue`
* new helper function `binarySearch` (for https://github.com/kaltura/playkit-js-hls/pull/157)
Solves FEC-11761
Related to - 
https://github.com/kaltura/playkit-js-hls/pull/157 
https://github.com/kaltura/playkit-js-dash/pull/174
https://github.com/kaltura/kaltura-player-js/pull/512
https://github.com/kaltura/playkit-js-dual-screen/pull/52 …
=> feat(FEC-11761): expose stream timed metadata - phase 2

src/engines/html5/media-source/adapters/native-adapter.js, src/player.js, src/track/external-captions-handler.js, src/track/text-track.js, test/src/engines/html5/media-source/adapters/native-adapter.spec.js, test/src/player.spec.js
**issue:** the create _addTextTrackOffOption method of the player creates duplicated indexes every time duplicated languages are detected (and warning created);
**fix:** right now the index property of TextTrack is used as a unique identifier but in the other hand we don't mange it as such (the index is created in different places), so , the index management all moved to one place under the TextTrack class
related pr:
https://github.com/kaltura/playkit-js-dash/pull/182
https://github.com/kaltura/playkit-js-hls/pull/161
solves: FEC-11697  & FEC-11893 & FEC-11973
=> fix(FEC-11697): 2 captions are selected in the menu

docs/configuration.md, src/player.js, test/src/player.spec.js
add the option to set `playback.audioLanguage: 'auto'` and compare with the locale then 
Solves FEC-11964
=> feat(FEC-11964): Allow configuring player to auto-select audio track according to browser locale

docs/api.md, src/middleware/middleware.js, src/middleware/playback-middleware.js, src/player.js, test/src/middleware/middleware.spec.js, test/src/middleware/playback-middleware.spec.js
add setCurrentTime middleware
add support for middleware params chaining 
Solves FEC-11979
=> feat(FEC-11979): add setCurrentTime middleware

src/engines/html5/html5.js, test/src/engines/html5/html5.spec.js
Safari fires WAITING event once unmuting and immediately sends PLAYING
so prevent sending waiting event for too short buffering
Solves FEC-11904
=> fix(FEC-11904): Player_Web_Mac - The spinner appears when unmute the show

src/engines/html5/html5.js
4 is too high and breaks the player
Solves FEC-11619
=> fix(FEC-11619):  Player failed to change speed rate to 4

src/engines/html5/media-source/adapters/native-adapter.js
Handle a scenario of this._liveEdge (in native-adapter) being 0 in a live stream, which caused isOnLiveEdge to be true when it shouldn't be.
Resolves FEC-12431.
=> fix(FEC-12431): [WEB] - [O2CZ] Player_Web_MAC_Safari - The progress bar jumps front and back when seek

src/assets/style.css
solves: FEC-12479
related pr: https://github.com/kaltura/playkit-js-dash/pull/204
=> fix(FEC-12479): [Dash] - Subtitles are too small and not centered

src/player.js
**the issue:** 
when click on the cc button to disable caption and then occur the "change media" functionality the new video start with cc enabled.
when turn off the caption from the cc button the previous language variable not change to off and still storing the previous language.
the previous language viarable will be changed to off also when clicking cc button and not only when clicking "off" in the language button.
=> fix(FEC-12351): cc button changed to enable during change media

src/player.js
add z-index=1 when youtube engine element is loaded to the ui, to allow clicks on youtube's ui.
Solves FEC-12121
=> fix(FEC-12121): youtube UI is not responsive for clicks

src/player.js
**the issue:**
when playing a video with 608 captions and switching to a certain language, after refreshing, the default is "off" instead of the language that was chosen (and that was saved to local storage).
608 captions are loaded one after another (unlike from the manifest which loaded all together). So if the desired textLanguage is not arriving at the first captions load, the player [selects the ‘off’ and saves it](https://github.com/kaltura/playkit-js/blob/d87e7b13fc204157b9615c67949135f45efd17ae/src/player.js#L1194). then, when the captions file with the desired textLanguage is being loaded, the player ignores it.
**solution:**
since setDefaultTracks is being called every time a 608 caption is loaded, need to set the default text track also by the value that is …
=> fix(FEC-10833): captions not auto selected from the user preferences

src/player.js
**the issue:**
when captions are external and disabling cc button, captions are still shown on player.
player's API hideTextTrack() does not handle external captions.
- check if active text track is external and use hideTextTrack() API of externalCaptionsHandler
Solves FEC-12350
=> fix(FEC-12350): external captions shown while cc button disabled

src/event/fake-event-target.js
Rename fake-event-target logger to not conflict with children.
Resolves FEC-12596.
=> fix(FEC-12596): Related plugin doesn't load because of an exception

docs/configuration.md, src/player-config.js
Solves FEC-12189
pr: 
https://github.com/kaltura/playkit-js-dash/pull/194
=> fix(FEC-12189): Stream doesn't start if open a program with a bookmark

docs/api.md, flow-typed/types/text-style.js, src/track/text-style.js
solves: FEC-12648
**Findings:**
**1.** by Default, the player uses its own text displayer and not the browser's native one
**2.** there are two level of text style (in PKTextConfigObject type):
**textTrackDisplaySetting: PKTextTrackDisplaySettingObject,
textStyle: PKTextStyleObject,forceCenter: boolean,**
**3.** by default both of them work
**4.** in case you use the browser native text tracks (useNativeTextTrack set to true) - only textStyle works
**5.** in case you use Shaka text displayer (useShakaTextTrackDisplay set to true) - none of them work
=> fix(FEC-12648): Text style configuration is not working

src/player.js
shaka Text Track Displayer does not work unless  useNativeTextTrack set to true
solves: FEC-12691
related pr: 
https://github.com/kaltura/playkit-js-dash/pull/215,
https://github.com/kaltura/kaltura-player-js/pull/586
=> fix(FEC-12691): Shaka Text Track Displayer does not work unless  useNativeTextTrack set to true

src/track/text-style.js
solves FEC-12736
Regression of https://github.com/kaltura/playkit-js/pull/669/
=> FEC-12736 - fix regression where fontSize in % is not working

flow-typed/types/playback-config.js, src/player.js, src/track/track.js, test/src/track/track.spec.js
**the issue:**
when the language track is 639-2 iso code and it's not the 639-1 + additional latter.
(for example: Spanish, 639-1: "es" 639-2: "spa")
the player doesn't recognize the language and it doesn't do the match between codes.
add fields of extensionAudioLanguage and extensionTextLanguage to the configuration
in order to add additional checking in case the 639-2 iso code is totally different from the 639-1 iso code.
solves FEC-12679
=> fix(FEC-12679): ISO Code for Chinese and Spanish in Multi Audio

src/player.js
**the issue:**
Captions are read aloud by the screen reader. 
Since captions are intended for users who are blind or have visual impairments, the audio of the video is sufficient.
Remove aria-live attribute from the captions element. 
solves FEC-12727
=> fix(FEC-12727):Remove aria-live region from the captions

src/engines/engine-type.js, src/fullscreen/fullscreen-controller.js
**the issue:**
full screen button is not responsive for clicks in youtube media on ios devices.
**the root cause:**
in case of ios deivces the full screen is the native full screen. 
the webkitEnterFullScreen function works only on the video element.
we tried to call the function on the element that wrapped the youtube iframe.
in case of youtube media on ios devices we always call the enterInBrowserFullscreen function since we can't call the webkitEnterFullScreen.
=> fix(FEC-12122):[WEB][Youtube media][iOS][Safari][iPhone] - Full screen UI is not responsive for clicks

src/track/external-captions-handler.js
- When adding active cues - advance the cue index, but don't add active cues if they are are expired
- When removing active cues - use filter instead of splicing in a loop, which caused some cues to not be removed.
- Reset cue index on text track selection to force recalculation of the cue index
Resolves FEC-12686
=> fix(FEC-12686): Web - When changing the caption from RUS to JAP in the middle of the video, all of the past caption are shown at once

flow-typed/types/image-player-options.js, flow-typed/types/sources-config.js, src/engines/stream-type.js
solves FEC-12549
related prs: 
https://github.com/kaltura/kaltura-player-js/pull/598
https://github.com/kaltura/image-player/pull/1
https://github.com/kaltura/playkit-js-providers/pull/190
https://github.com/kaltura/playkit-js-ui/pull/718
=> feat(FEC-12549): Image Player Engine (playkitJS/v7)

docs/configuration.md, src/track/text-track-display.js
**issue:** we override the [positionAlign](https://developer.mozilla.org/en-US/docs/Web/API/VTTCue/positionAlign) on [VTTCue](https://developer.mozilla.org/en-US/docs/Web/API/VTTCue) with no [excepted values](https://developer.mozilla.org/en-US/docs/Web/API/VTTCue/positionAlign#value), so Firefox ignores other values and keep its default value - 'auto'
**fix:** changed the configuration to use the [excepted values](https://developer.mozilla.org/en-US/docs/Web/API/VTTCue/positionAlign#value), (and keep the old ones for backward  compatibility)
solves: FEC-12991
=> fix(FEC-12991): Left-positioned captions are centered on Firefox

src/track/external-captions-handler.js
FEC-12983 - fix cue index after seek back
=> fix(FEC-12983): fix regression external captions are not displayed after seek back

src/engines/html5/media-source/adapters/native-adapter.js
Support setting startTime 0.
Resolves FEC-13108.
=> fix(FEC-13108): Start time can't be set to 0 in loadMedia for live with dvr

src/player.js
- bug fix
**the issue:**
when playing a playlist and the audio should be muted- after playing a YT entry, the player is becoming unmuted for the next entry.
it seems that the playkit is checking the YT engine's `muted` value, while the youtube engine hasn't even loaded yet. Because of that, the autoplay handler is executing `onFallbackMutedAutoPlay` function instead of `onMutedAutoPlay` function. As a result, when playing a different entry after playing the YT one, the UI is unmuting the player- because of the `fallbackMutedAutoPlay` state.
**solution:**
at the point when we're checking the `muted` value, it is possible that the engine hasn't loaded yet (like in our case), so the muted value that we get is not reflecting the actual state of muted; the engine is returning …
=> fix(FEC-13227): video starts unmuted in playlist after playing YT entry

src/player.js
the issue:
when change captions to off and move to next entry captions changed back to be on.
the changes:
change in code if expression. remove if captions are off take the default so it will take what the user choose last, and add check is disable user cache then take the default.
=> SUP-37895: CC setting is not persisting until refresh

src/engines/html5/media-source/adapters/native-adapter.js
FEC-13217 - avoid accessing the this._videoElement.seekable.start(0) if 
this._videoElement.seekable.length <= 0
=> fix(FEC-13217) - add protection for DOM Exception IndexSizeError

docs/configuration.md, flow-typed/types/sources-config.js
add new configurations under `PKSourcesConfigObject` object:
- `seekFrom` - optional, number, in sec
- `clipTo` - optional, number, in sec
if configured, the above will be chained to the `playManifest` request and as a result, the video will play from the seekFrom position to the clipTo position.
**For example:**
configuring the following: `seekFrom=10`, `clipTo=20`, where the video duration is 40 sec.
the duration of the video that will be played as a result, would be 10 sec long, where the first frame will be the same as the frame of the original video at position 10; and the end frame will be the same as the frame of the original video at position 20.
**related PR-** https://github.com/kaltura/kaltura-player-js/pull/658
Solves FEC-13420
=> feat(FEC-13420): support start and end time of video

src/player.js
**the issue:**
when the textLanguage config is defined to "auto" and there is no previous language in the localSession when clicking on enable caption button nothing happen.
trying to find track with "auto" language and not real language 
when "captionsDisplay" is disabled change the attribute state to defaultLanguage (the playbackConfig.textLanguage after set the language for "auto")
=> fix(SUP-39574): Enable captions button is not working

flow-typed/types/playback-config.js, src/player.js
set the playbackRate according to the value in localStorage (if exists).
**related PR:** https://github.com/kaltura/kaltura-player-js/pull/667
Solves FEC-13462
=> feat(FEC-13462): set the playbackRate according to the value in localStorage

src/player.js
- handle the `playbackRate` after `medialoaded` event, in order to overcome race condition, where the playbackRate is being overwritten; the engine is re-initializing the playbackRate after the media is loaded.
Solves FEC-13462
=> feat(FEC-13462): handle the playback rate after medialoaded event

src/engines/html5/media-source/adapters/native-adapter.js
if useMediaOptionAttribute is true then first take all mediaOptionAttribute which is an object that passes as is the webLG options as defined in https://webostv.developer.lge.com/develop/guides/mediaoption-parameter If abrEwmaDefaultEstimate is defined so it passes it as override on top of the mediaOption in the 'option.adaptiveStreaming.bps' object
=> feat: support full webOS mediaOption object

src/engines/html5/media-source/adapters/native-adapter.js
the logic of removing source tag depends on config which is reset in the super destroy method so need to run it before
=> fix: remove source tag before config is reset

src/player.js
**issue:**
In Edge browser when video is paused and captions enabled, when seeking in seekbar the caption are not displayed on the player.
**solution:**
The issue is caused by old fix made here - https://github.com/kaltura/playkit-js/pull/147 The original issue no longer reproducible so removed the old patch.
solves [ADA-82](https://kaltura.atlassian.net/browse/ADA-82)
[ADA-82]: https://kaltura.atlassian.net/browse/ADA-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ADA-82): Caption Texts are Not Showing when Moving Cursor in Time Bar

src/track/text-track.ts, src/utils/resize-watcher.ts
Restore window.* to protect against missing properties on the global context
=> fix: restore window object where needed

.github/workflows/create_patch_version.yaml
=> fix(FEC-13641): Add 'patch' tag to npm versions

src/player.ts
- bug fix.
**the issue:**
when loading a playlist with youtube entry and media that has dualscreen, and playing the dualscreen media- the dualscreen player is not clickable. in addition, the interaction with the player gui area is also "blocked".
we are adding `z-index = 1` to the engine element in case it is a youtube engine. when switching to the dual media (or just not a YT entry), it is blocking the interaction with the player in the gui area (play/pause), which includes blocking interaction with the secondary player (aka the dualscreen).
**solution:**
remove the value of `z-index` in case the engine is not youtube.
Solves FEC-13594
=> fix(FEC-13594): playlist with youtube blocks interaction with player

src/enums/media-type.ts, src/types/media-types.ts, src/types/sources-config.ts
Add mediaEntryType under source-config
Part of [#379 ](https://github.com/kaltura/kaltura-player-js/pull/739)
Solves [SUP-41054](https://kaltura.atlassian.net/browse/SUP-41054)
[SUP-41054]: https://kaltura.atlassian.net/browse/SUP-41054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-41054): Playlist Chapter display issue with Live to VOD

docs/configuration.md, flow-typed/types/text-config.js, flow-typed/types/text-track-display-setting.js, src/engines/html5/html5.ts, src/engines/html5/media-source/base-media-source-adapter.ts, src/player-config.js, src/player.ts, src/track/external-captions-handler.ts, src/track/text-style.ts, src/track/text-track-display.ts, src/track/track.ts, src/types/interfaces/engine.ts, src/types/interfaces/media-source-adapter.ts, src/types/text-config.ts, src/types/text-style.ts, src/types/text-track-display-setting.ts, src/utils/index.ts, src/utils/styles.ts, tests/e2e/player.spec.js
1. Add `textAlign`: string (left/right/center) property to `config.text.textStyle`;
2. Remove `align` option form `config.text.textTrackDisplaySetting`;
3. Remove `forceCenter` option from `config.text`
4. upd documentation;
5. handle caption alignment based on `config.text.textStyle.textAlign` configuration;
6. upd tests;
=> feat(FEC-13664): Add the ability to configure default alignment of captions on the player #

src/track/external-captions-handler.ts, src/track/text-style.ts
issue:
in advances captions settings for ios change background color and change font size didn't applied
solution:
add font-size to css attribute
add background using gradient (due to known issue in ios) to css attribute 
resolve [SUP-42112](https://kaltura.atlassian.net/browse/SUP-42112)
[SUP-42112]: https://kaltura.atlassian.net/browse/SUP-42112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-42112): Advanced Caption Settings not working in iOS

.github/workflows/run_canary.yaml, README.md, src/track/external-captions-handler.ts, src/track/text-style.ts
=> Moshe maor kaltura patch 4

src/track/text-track-display.ts
Overwrite default caption alignment (case when caption cues has native alignment but user set custom alignment in caption menu) 
resolves: https://kaltura.atlassian.net/browse/FEC-13979
=> fix(XDR-3359): fix default caption alignment

src/engines/html5/html5.ts
**Issue:**
In dual screen player the pip option is disabled by adding disablePictureInPicture on the video element. was done here - [FEC-13591](https://kaltura.atlassian.net/browse/FEC-13591).
As a result from that when clicking on the pip button error is thrown and the video is frozen
**Solution:**
Call to pip function only if disablePictureInPicture is not true
Solves [SUP-43040](https://kaltura.atlassian.net/browse/SUP-43040)
[FEC-13591]: https://kaltura.atlassian.net/browse/FEC-13591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SUP-43040]: https://kaltura.atlassian.net/browse/SUP-43040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-43040): v7 player issues when using picture-in-picture (pop-out)

src/engines/html5/html5.ts, src/engines/html5/media-source/base-media-source-adapter.ts, src/player.ts, src/types/interfaces/engine.ts, src/types/interfaces/media-source-adapter.ts
- Add setCachedUrls API
- Pass the arguments to the adapter setCachedUrls API once an adapter is available
Related PRs:
https://github.com/kaltura/playkit-js-dash/pull/262
https://github.com/kaltura/kaltura-player-js/pull/792
Resolves FEC-13946
=> feat(FEC-13946): Player core - Use shaka preload mechanism during playlist playback

src/player.ts
**Issue:**
Iframe elements are labeled with uiConf/xxxxxx (the last parameter in the src url) in iframe lists (on screen readers) and not name.
**Solution:**
Add title element with the entry name
Solves [ADA-6](https://kaltura.atlassian.net/browse/ADA-6)
[ADA-6]: https://kaltura.atlassian.net/browse/ADA-6?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ADA-6): v7 player (accessibility) - Frames for Video Players Aren't Labeled

src/player.ts
Add validation for call to engine setCachedUrls, since non html5 engines don't have this API
Resolves FEC-14058
=> fix(FEC-14058): Playlist - Loading Youtube and Image entries throws an error

src/player.ts
Add function to change quality on child entries in dual screen.
part of - https://github.com/kaltura/playkit-js-dual-screen/pull/155
solves [SUP-38407](https://kaltura.atlassian.net/browse/SUP-38407)
[SUP-38407]: https://kaltura.atlassian.net/browse/SUP-38407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-38407): [GaTech] [Multistream - V7 Player] Child entries not loading high quality flavor assets

src/track/text-track-display.ts
issue: 
when use position configuration under text-> textTrackDisplaySetting the configuration is not apply
solution:
change the align is being checked when put the position from styleText configuration to textTrackDisplaySetting configuration
* regression from version 3.17.13
solved [SUP-44939](https://kaltura.atlassian.net/browse/SUP-44939)
[SUP-44939]: https://kaltura.atlassian.net/browse/SUP-44939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-44939): [Player] Numeric Position not working on left-positioned captions, AWS

docs/configuration.md, flow-typed/types/playback-config.js, src/player-config.js, src/player.ts, src/track/audio-track.ts, src/track/track.ts, src/types/metadata-config.ts, src/types/playback-config.ts
resolves: https://kaltura.atlassian.net/browse/FEC-14087
=> feat(FEC-14087): define audio-description audio tracks

src/player.ts, src/track/external-captions-handler.ts
- Add a new API for the player to set [seekFrom, clipTo] values
If seekFrom or clipTo are set
- Filter caption cues outside the [seekFrom, clipTo] range
- Translate the cues within the [seekFrom, clipTo] range into a time range that starts from 0
Related PR: https://github.com/kaltura/kaltura-player-js/pull/876
=> fix(SUP-37490): Align captions with clipTo/SeekFrom Values in PlayManifest

src/player.ts, src/track/external-captions-handler.ts
- [-] new unit / functional tests have been added (whenever applicable)
- [-] Docs have been updated
=> FEC-14226: protect against missing textTracks in fast entry change

src/player.ts
Issue:
Video element get focus in Firefox browser.
Fix:
Add tabIndex="-1" on the video element
solves [ADA-1788](https://kaltura.atlassian.net/browse/ADA-1788)
[ADA-1788]: https://kaltura.atlassian.net/browse/ADA-1788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ADA-1778): [ORS] - Firefox playerkit - Focusable but hidden/unlabeled elements in tabbing order

src/error/category.ts
Adding error category to site restriction and scheduled restriction
Part of - https://github.com/kaltura/playkit-js-ui/pull/970, https://github.com/kaltura/kaltura-player-js/pull/897, https://github.com/kaltura/playkit-js-providers/pull/245
Resolves [SUP-45003](https://kaltura.atlassian.net/browse/SUP-45003)
[SUP-45003]: https://kaltura.atlassian.net/browse/SUP-45003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-45003): [IKEA Ingka] - past scheduled embedded entries will show a wrong error message for V7 player

src/player.ts
Fix for https://kaltura.atlassian.net/browse/FEC-14257
=> fix(FEX-14257): fix duplicating cues safari

src/engines/html5/html5.ts
Issue:
On safari, when PiP is open, video ends and try to play it again with start over, nothing happened.
Safari PiP locks the video in an "ended" state, preventing .play() from restarting playback unless the video is explicitly paused and its currentTime is reset.
Unlike Chrome, Safari doesn't automatically reset currentTime to 0 when a video ends.
Fix:
Added a browser check to detect Safari using the user agent.
Applied a conditional reset of the video (pause() and currentTime = 0) only when:
The browser is Safari.
The video is in Picture-in-Picture (PiP) mode.
solved [SUP-46985](https://kaltura.atlassian.net/browse/SUP-46985)
[SUP-46985]: https://kaltura.atlassian.net/browse/SUP-46985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix (SUP-46985): Replay button unresponsive when PiP is activated

src/player.ts
**Issue:**
When play an audio entry with caption on safari, captions are missing.
Unlike Chrome, Safari ignores text tracks when there's no visual component. This is why it's needed manual processing.
**Fix:**
Check condition for audio entry.
solved [SUP-45555](https://kaltura.atlassian.net/browse/SUP-45555)
[SUP-45555]: https://kaltura.atlassian.net/browse/SUP-45555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-45555): Missing Captions in SafariMac and iOS

src/player.ts
issue:
when set textLangauge config to auto captions mark as default are the one that see on screen
root cause:
when set textLangauge config to auto, the order that captions is choosen is first by locale, and in case no captions with locale langauge then it will choose according default.
solution:
change the order of cations are choose to first take the default and if no default then choose according the locale
solve [SUP-47317](https://kaltura.atlassian.net/browse/SUP-47317)
[SUP-47317]: https://kaltura.atlassian.net/browse/SUP-47317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-47317): [Saxion] inquiry about correct work of default captions

src/player.ts
**Issue:**
When an entry that is part of a playlist got an error, it keeps the previous entry instead of the current entry to play.
**Fix:**
Add a case inside playNext, when a playlist that is part of the entry gets error.
solved [SUP-48030](https://kaltura.atlassian.net/browse/SUP-48030)
[SUP-48030]: https://kaltura.atlassian.net/browse/SUP-48030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-48030): player V7 display issue on playlist with blocked and non-blocked content

src/player.ts
**ths issue:**
in a playlist, when switching between "regular" videos and YT videos, at some point when clicking on the video area of a yt video, for play/pause actions, it doesn't react.
there are duplicates of engine elements for youtube - which grabs the clicks and prevent from play/pause to take any affect.
every time when switching from a non-youtube video to a youtube video, it adds a yt-engine element under the playkit-container.
**solution:**
when switching engines, in case of a youtube video - cleanup yt engine element before appending the current yt engine element.
Solves FEC-13481
=> fix(FEC-13481): YouTube entries inside playlist cause wrong behavior

docs/configuration.md, src/player.ts, tests/e2e/track/default-tracks.spec.js
- Updates the documentation for the `prioritizeAudioDescription` configuration option to clarify its behavior for true, false, and undefined values.
- Prioritize audio description tracks as the default when `prioritizeAudioDescription` is true.
- Prioritize regular audio tracks as the default when `prioritizeAudioDescription` is false.
- Default to regular audio tracks and disable prioritization in the tracks list when `prioritizeAudioDescription` is undefined.
- Refactors selection to more clearly handle user preferences and fallback logic for audio tracks.
=> feat(FEC-14583): Fix default audio track + Update prioritizeAudioDescription description in configuration.md file

src/player.ts
- Adds a helper function `getAudioTrackPreferredLanguage` to select audio tracks based on the user's preferred browser languages.
- Uses navigator.languages for preferred language selection, with fallback to Locale.language.
- Prioritizes matching non-audio-description tracks to preferred languages, otherwise selects the first non-audio-description track.
- Refactors `getAudioLanguage` to use the new preferred language logic for audio track selection.
- Improves audio language selection to better respect user/browser language preferences.
[FEC-14583](https://kaltura.atlassian.net/browse/FEC-14583)
[FEC-14620](https://kaltura.atlassian.net/browse/FEC-14620)
[FEC-14583]: https://kaltura.atlassian.net/browse/FEC-14583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …
=> feat(FEC-14583): Fix default audio track to check all user's preferred languages and not only current one
