kaltura/playkit-js

src/plugin/base-plugin.js
Set all plugins names to lead with capital letter for logging consistency.
=> capitlize name for logger

src/engines/html5/html5.js
=> chore: fix flow error

src/drm/base-drm-protocol.js, src/drm/fairplay.js
Add logger to base drm protocol.
=> chore: add logger to base drm protocol

karma.conf.js, test/src/engines/html5/media-source/adapters/native-adapter.spec.js, test/src/player.spec.js
=> chore: set default mocha timeout to 10000

.eslintrc.json, package.json, src/playkit.js, webpack.config.js, yarn.lock
Define globals and expose them to build via webpack Define plugin.
Currently we add the entire package JSON file to the build.
=> chore: define globals via webpack DefinePlugin

src/engines/html5/media-source/adapters/native-adapter.js, src/event/event-manager.js, src/player.js, test/src/event/event-manager.spec.js, test/src/player.spec.js, test/src/utils/test-utils.js
The application which uses the playkit-js SDK will need to use getView method to get the player element and it will control attaching it to the DOM
=> feat: player doesn't attach itself to parent

src/event/events.js, src/player.js, test/src/event/events.spec.js
fired upon mute change, payload contains current mute status
=> feat(FEC-7182): add VOLUME_MUTE_CHANGE event

CHANGELOG.md
=> chore: fix duplicates in CHANGELOG.md

src/player.js
=> chore: organize player api using editor-fold 

src/player.js
textStyle object initialized so the UI could understand what the initial textStyle is and show accordingly the captions style options.
=> patch: initialization of textStyle object

CHANGELOG.md, flow-typed/interfaces/engine.js, flow-typed/interfaces/media-source-adapter.js, flow-typed/interfaces/plugin.js, package.json, src/engines/html5/html5.js, src/engines/html5/media-source/adapters/native-adapter.js, src/engines/html5/media-source/base-media-source-adapter.js, src/event/events.js, src/player.js, src/plugin/base-plugin.js, src/plugin/plugin-manager.js, src/state/state-manager.js, src/utils/poster-manager.js, src/utils/util.js, test/src/engines/html5/html5.spec.js, test/src/engines/html5/media-source/adapters/native-adapter.spec.js, test/src/event/events.spec.js, test/src/player.spec.js, test/src/plugin/base-plugin.spec.js, test/src/plugin/plugin-manager.spec.js, test/src/plugin/test-plugins/colors-plugin.js, test/src/plugin/test-plugins/numbers-plugin.js, test/src/state/state-manger.spec.js, test/src/utils/poster-manager.spec.js
* Change media added logic.
* Requires to add reset() api to most of our components.
* Requires to change destroy API of engine and MSE adapters to return promises (since shaka destroy API returns promise).
* Lifecycle events of change media  were added.
=> feat: change media

src/player.js, src/track/track.js, test/src/track/track.spec.js
=> chore: use toLowerCase on langComparer

karma.conf.js, src/player.js, test/src/player.spec.js
some browsers have an issue on seeking to duration. so add an offset to seek safety.
=> fix(FEC-7046): seek to duration safety using offset

src/event/events.js, src/player.js, test/src/event/events.spec.js, test/src/player.spec.js
Fire an event on text style changed, mainly for local storage.
=> feat(cvaa): add TEXT_STYLE_CHANGED event

.travis.yml, README.md
Fixes Travis CI hrefs, plus README typos.
=> fix(README): typos and travis ref

.eslintrc.json, src/drm/fairplay.js, test/src/drm/fairplay.spec.js
adding validation to the DRM fairplay server response + adding tests.
adding chai to the global variables to eslint
=> chore(FEC-7299): add validation to fairplay drm server response 

src/drm/fairplay.js
Fix access to instance method instead of static on a static object
=> fix(FEC-7348): fix fairplay exception

src/engines/html5/media-source/adapters/native-adapter.js, test/src/engines/html5/media-source/adapters/native-adapter.spec.js
do not parse track without language or label
=> fix(FEC-7345): only off option appears in text track menu (safari)

flow-typed/interfaces/engine.js
Add missing arg in canPlaySource interface.
=> fix: update canPlaySource API in engine interface

src/error/code.js
add Hlsjs error code 3023 (HLS_BUFFER_STALLED_ERROR)
=> fix: add HLS_BUFFER_STALLED_ERROR error code

docs/configuration.md, docs/source-selection-logic.md
=> docs: source selection logic

src/engines/html5/media-source/adapters/native-adapter.js, src/engines/html5/media-source/base-media-source-adapter.js
=> chore: use EventType to get the playkit events

src/engines/html5/capabilities/html5-autoplay.js
Change the promise implementation a bit.
=> fix(FEC-7371): video fails to play on old browsers or browsers with data saver mode on (cont.)

flow-typed/interfaces/drm-protocol.js, src/drm/base-drm-protocol.js, src/engines/html5/media-source/adapters/native-adapter.js
Remove destroy from `DrmProtocol` interface since it has no meaning and we're overriding the old protocol with the new protocol on change media.
=> fix(FEC-7970): Change media from DRM to DRM is not working

docs/configuration.md, flow-typed/types/media-source-options.js, src/player-config.json, src/utils/jsonp.js
* Set default value to `false`.
* Update docs.
* Reduce timeout in JSONP util.
=> fix(FEC-8026): external OTT VOD/Live media doesn't works on IE 11

test/src/player.spec.js, test/src/utils/test-utils.js
moved getConfigWithLabel to the player.spec. from the test-utils.js
=> fix(FEC-7330): removed flow annotation which failed hls build

src/engines/html5/capabilities/html5-autoplay.js
If the device is in data saver mode terminate the capabilities check for autoplay since we know the answer.
=> feat: data saver mode optimisation check

CHANGELOG.md, package.json, src/assets/style.css, src/event/event-type.js, src/player.js, test/src/event/event-type.spec.js, test/src/player.spec.js
Trigger `MEDIA_LOADED` event when media is loaded (`readyPromise` is resolved)
=> feat: media loaded event

docs/configuration.md, src/engines/html5/media-source/adapters/native-adapter.js, src/player-config.json
Change default start time to -1.
=> fix(FEC-8203): Live with DVR is not playing live edge in first play

src/player.js
=> fix(FEC-8202): Session ID isn't sent when reporting analytics #118

docs/configuration.md
=> docs(FEC-8243): disable plugin docs

src/player.js, src/plugin/base-plugin.js, src/plugin/plugin-manager.js, test/src/plugin/plugin-manager.spec.js
added '_disabled' property in the base plugin. in can be set using the setter.
=> feat(FEC-8243): allow to disable specific plugins

src/state/state-manager.js
added condition before the debug statement so it won't bomb the logs (if timeupdate don't write transition)
=> fix(FEC-8330): remove 'timeupdate' logs

src/track/external-captions-handler.js, test/src/track/external-captions-handler.spec.js
adding WEBVTT at the begining of the vtt file.
=> fix(FEC-8365): srt files are not shown

src/track/external-captions-handler.js, test/src/track/external-captions-handler.spec.js
=> fix(FEC-8366): seek to an already started caption does not work

src/track/external-captions-handler.js
changed the time update logic to be more readable.
=> fix: refactor 'timeupdate' logic

src/engines/html5/media-source/adapters/native-adapter.js
=> fix(FEC-8376): reverting the fix

src/player.js
move the _maybeAdjustTextTracksIndex to _updateTracks as it's more suitable there - it's related to text tracks.
=> chore(refactor): move _maybeAdjustTextTracksIndex to _updateTracks

src/playkit.js
=> feat: expose logger util

src/player.js
Support ended attribute also as part of the player api.
=> feat: add ended state

src/ads/ad-error-code.js
update code name to AD_UNDEFINED_ERROR
=> fix(ads): update UNDEFINED_ERROR code name

flow-typed/interfaces/engine.js, src/engines/html5/html5.js, src/error/code.js, src/event/event-type.js, src/player.js, test/src/player.spec.js
Adding Picture in picture API:
```
enterPictureInPicture()
exitPictureInPicture()
isInPictureInPicture()
isPictureInPictureSupported()
```
Exposing 3 events (HTML5 events):
Chrome events:
`enterpictureinpicture` (after entering PIP)
`leavepictureinpicutre` (after exit PIP)
Safari event:
`webkitpresentationmodechanged` (when transitioning from inline to PIP / PIP to inline)
=> feat(FEC-8277): Picture in Picture support

test/src/track/external-captions-handler.spec.js
=> chore: skip failed tests

src/engines/html5/html5.js
Removed by mistake on cast merging.
=> fix: add handle media error

src/engines/html5/media-source/adapters/fairplay-drm-handler.js
1. added error data when there is xhr error
2. throwing an error if the xhr loaded correctly, but the status returned by the server indicating an issue.
=> feat(FEC-8639): fairplay uDRM error handling refining

src/state/state-manager.js, test/src/state/state-manger.spec.js
Support seek on ended transition
=> feat(FEC-8682): end screen

src/track/external-captions-handler.js
change the order we call the functions
protect calling to cues so we won't call it on undefined.
=> fix(FEC-8779): change media does not work if external caption is shown

flow-typed/interfaces/engine.js, src/engines/html5/html5.js, src/player.js, src/track/external-captions-handler.js, src/track/text-style.js, src/track/text-track-display.js
instead of using CSS class to override the vtt style, we will style each caption according to the settings.
=> fix(FEC-8572): change the way the player compute text tracks font size

src/ads/ad-event-type.js
=> feat(FEC-8675): add ad progress and buffer event to player

docs/configuration.md, docs/drm-system.md, flow-typed/interfaces/media-source-adapter.js, flow-typed/types/drm-config.js, src/track/external-captions-handler.js
=> docs(FEC-8809): new keySystem DRM option

flow-typed/types/ad-options.js, src/ads/ad.js
add `system` to the ad options
=> fix: ad system is missing in the ad options

docs/configuration.md, flow-typed/types/log-level.js, flow-typed/types/player-options.js, karma.conf.js, src/player-config.js, src/player.js, src/utils/logger.js, test/src/player.spec.js
add configuration logger options.
handler to output logs with customize function.
option to remove playerVersion from log.
=> feat(FEC-9023): More logger options

docs/configuration.md, src/player.js, test/src/player.spec.js, test/src/utils/test-utils.js
Fixed typo playbackRate to `playbackRates`
=> fix: typo in playbackRates config

src/utils/env.js, src/utils/util.js
add protocol for Samsung Smart TV bug to all plugins
=> fix(FEC-9237): add app protocol to playkit utils

src/engines/html5/html5.js, src/engines/html5/media-source/adapters/native-adapter.js
added recovery to continue playback from the same point (code effects only native-adapter)
=> fix(FEC-8873): fatal error occurs when coming back from idle in Native HLS IOS

flow-typed/interfaces/media-source-adapter.js, src/engines/html5/media-source/base-media-source-adapter.js
add check for MSE adapter to make sure we'll select the correct adapter for devices
=> fix(FEC-9342): Disable shaka on iOS

.babelrc, flow-typed/interfaces/ads-plugin-controller.js, flow-typed/types/ad-break.js, flow-typed/types/ad-pod.js, flow-typed/types/ad.js, src/ads/ads-controller.js, src/player-config.js
* Add `advertising` config which holds  ad breaks to play by position
* Implement `playAdNow` api
=> feat(FEC-9323): advertising configuration

src/utils/env.js
=> fix(FEC-9362): IPad OS wasn't recognised on UAParser

src/utils/env.js
add user detection for dev or canary Chromium Edge
=> fix(FEC-9379): add detection for chromium Edge

src/engines/html5/media-source/adapters/fairplay-drm-handler.js
To be compatible with different DRM server
Solves FEC-9427
=> fix(FEC-9427): use response type in xhr arraybuffer for Fairplay request

src/playkit.js, src/utils/index.js
export resize-watcher as part of the library public api
=> feat(FEC-9282): export resize-watcher

src/event/event-type.js, src/player.js
* `USER_GESTURE` event
* `get hasUserInteracted` api
=> feat: new USER_GESTURE event and api

flow-typed/types/ad.js
support config ad as xml (vast response)
=> feat(FEC-9469): ad layout - xml response

src/player.js
adding aria-live "polite" to the captions element
=> feat(FEC-9462): enable caption reading by screen reader

flow-typed/types/ad.js
add `bumper` config to the `PKAdObject` type
=> feat(FEC-9470): ad layout - bumper support

src/engines/html5/html5.js, src/event/event-type.js, src/player.js
Add new event for play failed.
=> fix(FEC-9480): there isn't event for play promise failed just autoplay failed

docs/configuration.md, src/engines/html5/media-source/adapters/fairplay-drm-handler.js, src/engines/html5/media-source/adapters/native-adapter.js, test/src/engines/html5/media-source/adapters/fairplay-drm-handler.spec.js, test/src/engines/html5/media-source/adapters/native-adapter.spec.js
Support `requestFilter/responseFilter` returning promise
=> feat(FEC-9452): async request/response filter handlers

src/engines/html5/media-source/adapters/native-adapter.js, test/src/engines/html5/media-source/adapters/native-adapter.spec.js
for reloading media add attach detach implemention
Solve FEC-9523.
=> fix(FEC-9523): add attach detach implemention

src/ads/ad-error-code.js, src/error/code.js
Error codes fixed:
CAST_CUSTOM_MESSAGE_PARSING_ERROR: 100002 ==> 10002
VAST_UNEXPECTED_DURATION_ERROR: 8201 ==> 8202
Solves FEC-9650
=> fix(FEC-9650): fix incorrect error codes

src/player.js, src/utils/util.js
if provided a url in the config externalCSS we load and append the style to the document header
solves FEC-9649
=> feat(FEC-9649): loading external CSS

src/utils/env.js
Move the internal kaltura-player-js env query utils to here so we can reuse them across playkit repos.
=> chore: add more environment queries

src/utils/util.js
Failed cause there was no existing link to append before.
Instead just adding the link tag at the end of the header
solves FEC-9649
=> feat(FEC-9649): css not loaded in embed page

src/player.js, test/src/player.spec.js
The ready promise rejected only when a critical error occurred
this makes the player ready before it actually loads the source
Solves FEC-10312
=> fix(FEC-10312): ready promise rejected in recoverable error

package.json, yarn.lock
Since https://github.com/conventional-changelog/standard-version/issues/539
=> chore: downgrade to standard-version 6

flow-typed/types/video-dimensions.js, src/engines/html5/media-source/adapters/native-adapter.js, src/player.js
issue: the native player doesn't provide analytics data about the video track.
solution: check the videoHeight, videoWidth if it changed the track change event triggered.
Solve: FEC-10146.
=> feat(FEC-10146): Add native video track analytics data

src/fullscreen/fullscreen-controller.js
exit from PiP before applying in-browser fill screen
Solves FEC-10514
=> fix(FEC-10514): iOS14 - wrong UI on inBrowserFullscreen from PiP

src/drm/fairplay.js
check environment drm support by `!!window.WebKitMediaKeys`
=> fix(FEC-10562): add wkwebview fairplay support

.babelrc
change modules value back to default.
=> build: change modules flag to default

src/fullscreen/fullscreen-controller.js, test/src/fullscreen/fullscreen-controller.spec.js
Issue: the isFullscreen() API checks the document element.
Solution: local state for each player and verification of fullscreen promise resolved
=> fix(FEC-10537): When multi players on page, isFullscreen() API returns true for all of them

src/utils/util.js
Issue: config with instance object merged like object.
Solution: check if it's an instance of class and merge it.
=> fix(FEC-10324): class instances merged like simple object

src/engines/html5/media-source/adapters/native-adapter.js
return promise which will be resolved or rejected at the end of reset.
=> fix(FEC-10662): incorrect flow in destroy process

src/engines/html5/media-source/base-media-source-adapter.js
Add protection against negative values on live playback.
=> fix(FEC-10816): Invalid currentTime values on start of live DASH

flow-typed/types/text-config.js, src/player.js, src/track/text-style.js, test/src/player.spec.js
create new instance instead of changing the current instance and add helper to make a new object base config or make config base on current object.
=> fix(FEC-10766): create static method for copy instead inner config

docs/api.md, docs/configuration.md, flow-typed/types/sources-config.js, src/player-config.js, src/player.js
move startTime to the sources config so it will take place only on the a specific source.
=> feat(FEC-10686): move startTime config from playback to sources

package.json
husky entry is missing on package.json.
=> chore: lint-staged linters doesn't running on commit 

docs/configuration.md, flow-typed/types/text-config.js, flow-typed/types/text-track-display-setting.js, src/player.js
Solves FEC-10924
See https://github.com/kaltura/kaltura-player-js/pull/403
=> fix(FEC-10924): add type for textTrackDisplaySetting

flow-typed/types/ad-options.js
add vpaid optional param on PKAdOptions
=> feat(FEC-10970): expose vpaid field on ad object

flow-typed/types/text-config.js
add useShakaTextTrackDisplay to text config
blocks https://github.com/kaltura/kaltura-player-js/pull/432
=> fix(FEC-11126): add useShakaTextTrackDisplay to text config

src/engines/html5/media-source/adapters/fairplay-drm-handler.js
Support `withCredentials` on updated request.
=> feat(FEC-11091): add support for XMLHttpRequest.withCredentials in request filter 

src/state/state-manager.js, test/src/state/state-manger.spec.js
Don't change the state on non-fatal error
Solves FEC-11215
=> fix(FEC-11215): forward and rewind controls are disabling

docs/configuration.md, flow-typed/interfaces/engine.js, flow-typed/types/restrictions-types.js, src/engines/html5/html5.js, src/engines/html5/media-source/adapters/native-adapter.js, src/engines/html5/media-source/base-media-source-adapter.js, src/player-config.js, src/player.js, src/playkit.js, src/track/track.js, src/utils/restrictions.js, test/src/player.spec.js, test/src/track/external-captions-handler.spec.js
add an API applyABRRestriction to apply ABR restrictions and show only available tracks after restriction.
=> feat(FEC-10980): Enable setting ABR settings on-the-fly

src/utils/util.js
Add support for passing timeout duration and timeout handler to `execute` util.
=> feat(FEC-11226): add support for passing timeout duration and timeout handler to xhr request

docs/api.md, flow-typed/interfaces/engine.js, flow-typed/interfaces/media-source-adapter.js, src/engines/html5/html5.js, src/engines/html5/media-source/adapters/native-adapter.js, src/engines/html5/media-source/base-media-source-adapter.js, src/player.js, test/src/engines/html5/media-source/adapters/native-adapter.spec.js
expose the current time of the video element in live streams
=> feat(FEC-10817): expose the current time of the video element in live streams

flow-typed/interfaces/media-source-adapter.js, src/engines/html5/media-source/adapters/native-adapter.js, src/engines/html5/media-source/base-media-source-adapter.js
Issue: native captions don't change to disable in change media.
Solution: always disable native text tracks on change media.
=> fix(FEC-10832): captions not shown in change media from media with 608 captions

docs/api.md, flow-typed/interfaces/engine.js, src/player.js
To calculate the preview image in KP we need to get the videoHeight and videoWidth so I exposed them in the core player
needed for https://github.com/kaltura/kaltura-player-js/pull/466
Solves FEC-11402
=> fix(FEC-11402): preview doesn't work in video ratio different than 16:9

.travis.yml, karma.conf.js
Due to changes in chrome - test page throws "too many WebMediaPlayers" and tests are broken.
https://bugs.chromium.org/p/chromium/issues/detail?id=1232649#c23
Adding '--max-web-media-player-count=1000' flag to override till chrome releases a fix next version
=> test: fixing automation tests after chrome restrictions

flow-typed/types/ad-options.js
Adding streamId to PKAdOptions.
Solves FEC-10598.
=> fix(FEC-10598): add streamId to PKAdOptions

src/playkit.js
=> fix(FEV-1020): [P2] Image player - Create image player component

docs/api.md, flow-typed/interfaces/engine.js, src/engines/html5/html5.js, src/player.js
- add addTextTrack API to player
- add addTextTrack API to engine
- update docs 
Solves FEC-11540
=> feat(FEC-11540): Cue-Point Manager

src/event/event-type.js
expose new event - `SOURCE_URL_SWITCHED`
Used by https://github.com/kaltura/playkit-js-broadpeak-smartlib/pull/6
Solves FEC-11166
=> feat(FEC-11666): Primary + Redirect token reports

package.json, yarn.lock
=> fix(FEC-11742): components with known vulnerabilities

src/playkit.js
Export setLogHandler function.
=> fix: export setLogHandler

flow-typed/types/text-track-cue.js, src/track/timed-metadata.js, test/src/track/timed-metadata.spec.js
=> test(FEC-11761): add unit test

.flowconfig, flow-typed/interfaces/drm-protocol.js, flow-typed/interfaces/engine.js, flow-typed/interfaces/media-source-adapter.js, src/drm/fairplay.js, src/engines/html5/html5.js, src/engines/html5/media-source/adapters/fairplay-drm-handler.js, src/engines/html5/media-source/adapters/native-adapter.js, src/engines/html5/media-source/base-media-source-adapter.js, src/player.js
expose the drm info on the player, (and as a result - on the engine and on the adatpter levels)
related prs:
https://github.com/kaltura/kaltura-player-js/pull/515
https://github.com/kaltura/playkit-js-dash/pull/175
https://github.com/kaltura/playkit-js-youbora/pull/82
solves: FEC-11785
=> fix(FEC-11785): [Youbora] - update youbora options for drm system that is used by the player

docs/api.md, docs/configuration.md, flow-typed/types/streaming-config.js, src/player-config.js
add `lowLatencyMode` configuration - default `true`
Solves FEC-10548
=> feat(FEC-10548): Low-Latency support

src/drm/fairplay.js
=> fix: log the fairplay support result

docs/configuration.md
update the doc
Solves FEC-12000
=> docs(FEC-12000): lowLatencyMode is false by default in samrt TV

docs/configuration.md, src/player-config.js
add loop config to documentation in 2 places:
- player-config.md
- configuration.md
Solves FEC-12270
=> docs(FEC-12270): update loop configuration in config MD files

docs/api.md, flow-typed/interfaces/engine.js, src/engines/html5/html5.js, src/player.js
=> fix(FEC-12252): getTextTracks should be called getNativeTextTracks

src/player.js
solves: FEC-12335
related prs:
https://github.com/kaltura/kaltura-player-js/pull/562
https://github.com/kaltura/playkit-js-ui/pull/687
=> fix(FEC-12335): Side Panel Item gets refreshed in every 'change media'

docs/configuration.md
=> doc:(update sourcesObject doc)

src/event/fake-event-target.js
add log when exception happens during event handler.
Solves [FEC-12275](https://kaltura.atlassian.net/browse/FEC-12275)
=> fix(FEC-12275): add log when event exception happens

docs/configuration.md
=> doc(FEC-12679):Update configuration.md

src/player.js
Fix FEC-12752 was introduced in FEC-10833
=> fix(FEC-12752) - ignore userCache for textLanguage if it is disabled

docs/configuration.md, flow-typed/types/text-style.js, src/track/vtt-cue.js
=> doc(FEC-12774): add some text api guide

src/player.js, src/track/text-track.js, src/track/track.js
solves FEC-12760
related pr: 
https://github.com/kaltura/playkit-js-hls/pull/183
https://github.com/kaltura/playkit-js-dash/pull/219
=> fix(FEC-12760): Blank Transcript Box In V7 Player

docs/configuration.md, src/engines/dropped-frames-watcher.js, src/player-config.js
FEC-12848-   "abr"."capLevelOnFPSDrop": false
=> fix(FEC-12848) - set abr.capLevelOnFPSDrop to default false.

docs/configuration.md, flow-typed/types/streaming-config.js
Add documentation for streaming.switchDynamicToStatic.
Related PR: https://github.com/kaltura/playkit-js-dash/pull/232
Resolves FEC-11970.
=> feat(FEC-11970): switch from dynamic manifest to static

src/engines/engine-type.js, src/enums/media-type.js
Add playbackType of type 'Image'
solves: FEC-12952
related prs:
https://github.com/kaltura/playkit-js-image-player/pull/5
https://github.com/kaltura/playkit-js-youbora/pull/108
=> fix(FEC-12952): Add playbackType of type 'Image'

docs/configuration.md
=> docs(FEC-11970):update configuration doc

flow-typed/interfaces/engine.js
=> fix(FEC-13144): add type for language parameter

docs/configuration.md
=> doc(FEC-11122):Update configuration.md

src/engines/html5/media-source/adapters/native-adapter.js
=> fix(FEC-13240): iOS safari will start from pos 0 instead of live edge

src/assets/style.css
=> fix(FEC-12852): When changing the background color of the player, the color is not changing on loading

docs/configuration.md, flow-typed/types/playback-config.js, src/player.js, test/src/player.spec.js
solves FEC-13321
related pr: https://github.com/kaltura/kaltura-player-js/pull/648
=> fix(FEC-13321): Captions default mode "Off" does not behave as expected

src/engines/html5/media-source/adapters/native-adapter.js
issue:
request to manage ABR in native HLS/DASH playback. 
need to support:options.adaptiveStreaming.bps, options.adaptiveStreaming.bps.start
=> feat(sup-39815):[LG WebOS] add support for webOS initial bitrate option

karma.conf.js
=> Dummy build

src/engines/html5/media-source/adapters/native-adapter.js
issue:
on hls native, playback freeze sometimes before the end
solution:
when time didn't change try to change currentTime forward to make start working
=> fix(SUP-39814):Playback freezes

src/engines/html5/media-source/adapters/native-adapter.js
change remove source from video element to be 1 step and not 2 steps
=> fix(SUP-40595):New player version

src/engines/html5/media-source/adapters/native-adapter.js
Reverts kaltura/playkit-js#741
=> Revert "fix(SUP-40595):New player version"

src/engines/html5/media-source/adapters/native-adapter.ts, src/engines/html5/media-source/base-media-source-adapter.ts, src/player.ts
=> fix(SUP-39894): fix bug in seekToLiveEdge

.github/workflows/create_patch_version.yaml
=> fix(FEC-13641): Add 'patch' tag to npm versions

.github/workflows/create_patch_version.yaml
Add 'patch' tag to npm versions
=> fix(/FEC-13641): Add 'patch' tag to npm versions

.github/workflows/create_patch_version.yaml, .github/workflows/run_canary.yaml, .github/workflows/run_patch.yaml, .github/workflows/run_tests.yaml
Remove canary patch version from canary versions track
=> Remove canary patch version from canary versions track

src/engines/html5/media-source/adapters/native-adapter.js
=> orenMChanges

src/engines/html5/media-source/adapters/native-adapter.js, src/engines/html5/media-source/base-media-source-adapter.js, src/player.js
=> Moshe changes

flow-typed/types/sources-config.js, src/engines/engine-type.ts, src/engines/stream-type.ts, src/enums/media-type.ts, src/types/sources-config.ts, src/types/stream-types.ts
base PR: https://github.com/kaltura/playkit-js-doc-player/pull/1
solves: https://kaltura.atlassian.net/browse/FEC-13507
=> feat(FEC-13507): Doc media type enums

src/error/category.ts, src/error/error.ts
Add meaningful error message to error slate feature.
**add new error categories:**
- MEDIA_NOT_READY: 12
- GEO_LOCATION: 13
- MEDIA_UNAVAILABLE: 14
for external plugins purposes- added a new filed `errorDetails` (includes title and message) to `Error` constructor.
Solves FEC-13652
=> feat(FEC-13652): add meaningful error message

src/engines/html5/media-source/base-media-source-adapter.ts
=> FEC-13956: Add window before MediaSource

src/engines/html5/media-source/base-media-source-adapter.ts
=> fix/FEC-13956:add window prefix MediaSource

src/engines/html5/media-source/base-media-source-adapter.ts
Fix signature of setCachedUrls to match the interface
=> chore: fix setCachedUrls signature

src/player.ts
Reverts kaltura/playkit-js#790
=> Revert "fix(FEC-14080): Accessibility fix for the top bar and the bottom bar"

src/error/category.ts
Add category to IP restriction
part of - https://github.com/kaltura/kaltura-player-js/pull/846, https://github.com/kaltura/playkit-js-ui/pull/936
solves [SUP-43014](https://kaltura.atlassian.net/browse/SUP-43014)
[SUP-43014]: https://kaltura.atlassian.net/browse/SUP-43014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-43014): [elearning] specified error message for v7 for IP restriction

src/engines/html5/media-source/adapters/native-adapter.ts, src/player.ts
Add video-filter div for use by ui when rendering bar gradients
Add class to indicate when native adapter displays native captions
Resolves FEC-14080
=> fix(FEC-14080): Accessibility fix for the top bar and the bottom bar

src/player.ts
=> FEC-14226: protect against case where tracks are not ready

src/player.ts
Fixes issue on https://kaltura.atlassian.net/browse/FEC-14257
=> fix(FEC-14257): Fix duplicating captions on Safari

src/player.ts
https://kaltura.atlassian.net/browse/FEC-14361
=> fix(FEC-14361): Fix for not showing captions

src/player.ts
Fix for feat https://kaltura.atlassian.net/browse/FEC-12711
Now it respects user selection on reload
=> feat(FEC-12711): Add default playback rate and respect users preference

src/error/category.ts
Reverts kaltura/playkit-js#822
=> Revert "fix(SUP-48817): Entries Under Moderation Are Still Playing"

src/engines/html5/media-source/adapters/fairplay-drm-handler-v2.ts, src/engines/html5/media-source/adapters/native-adapter.ts
Implement Fairplay DRM handler using modern safari EME APIs
Resolves FEC-14649
=> feat(FEC-14649): Integrate FPS Safari using Modern EME APIs
